docs/CactbotCustomization.md, docs/zh-CN/CactbotCustomization.md
This is re-PR'ed from quisquous/cactbot#6052
------
This is the following up for quisquous/cactbot#6047 , also fix several typos in English version.
According to [Microsoft's localisation guide](https://learn.microsoft.com/en-us/globalization/localization/ministyleguides/mini-style-guide-sim-chinese) and [vinta's 盤古之白 convince](https://github.com/vinta/pangu.js), this PR do the following:
- Add missing lines in the previous PR.
- Replace all polite `您` to a normal `你`.
- Insert spaces between Chinese characters and western characters or symbols (the `Pangu`-ism).
- Captalize all English words, unless it has a special spell rule.
------
cc @Echoring @ShadyWhite
=> docs: update zh-cn customisation guide

docs/TimelineGuide.md
Since it is implemented at https://github.com/MaikoTan/cactbot-highlight/pull/406 and released in version 0.6.0.
~~Please call me Sonic Maiko~~
Preview:
=> docs: remove future work for highlight

docs/TimelineGuide.md, resources/netregexes.ts, util/logtools/encounter_tools.ts, util/logtools/make_timeline.ts
(sorry for the git bork/closed PR - one more time...)
This PR should address the encounter sync drift referenced in quisquous/cactbot#5635 and quisquous/cactbot#6048, as well as the missing zone-seal sync referenced in quisquous/cactbot#5716.
There were a couple of separate but related issues that I found:
1. `encounter_tools` had not (yet) been updated to use `InCombat` lines to start encounters, even though `make_timeline` is inserting an `InCombat` sync at the start of a new timeline.
2. For fights that do not have zone seals, `encounter_tools` would fall back on using `playerAttackingMob` or `mobAttackingPlayer` regex. While this mostly still worked (with minor drift issues), it was also counting faerie healing actions as the start of the fight. I confirmed this was the case with the …
=> util: fix encounter start bug in make/test timeline scripts

docs/TimelineGuide.md, util/logtools/encounter_tools.ts, util/logtools/make_timeline.ts, util/logtools/split_log.ts, util/logtools/splitter.html, util/logtools/splitter.ts, util/logtools/web_splitter.ts
Adds a "Filter Log for Analysis" checkbox to the web splitter tool, and an `-af` | `--analysis-filter` argument to the `split_log` utility.  If this option is enabled, the log lines are run through a filter and only "useful"/"interesting" lines are emitted.
(I also added an `-na` | `--no-anonymize` argument to `split_log` to allow anonymization to be turned off -- it's on by default.  This was a TODO in the script already, and since I was already poking around, it made sense to kill two birds.)
The filter to determine whether a log line is useful/interesting should essentially mirror the regex that quisquous has previously shared and that's mentioned in the timeline guide, with one exception: I also added comparable LosesEffect (30) lines, since the loss of a debuff may also be …
=> util: add analysis filter to log splitter

util/logtools/make_timeline.ts
Closes #18.
(ref discussion in quisquous/cactbot#5943).
Instead of ignoring all abilities used by combatants with an empty name field, `make_timeilne` will now include entries in the timeline and the timeline ability table if the empty-name combatant uses a named ability.
=> util: improve empty-name actor logic in make_timeline

LICENSE, docs/LogGuide.md
fixes a URL typo introduced in #1
=> docs: fix Log Guide typo

docs/PatchUpdateChecklist.md, package.json, util/console_logger.ts, util/index.ts, util/query_xivapi.ts, util/xivapi.ts
Adds a new XIVAPI CLI query tool to util.  It's a lightweight script that fetches endpoint data, filters it based on a user-specified filter string, and outputs it as JSON to the console.  I put an early version of this together for looking into some of the data issues during the util script cleanup, and it was pretty helpful.  It's grown a bit since. 👀
More info on usage available by running `npm run query -- -h`.
Since it uses regex on user-supplied inputs, there's a lot of error handling needed to capture wonky user input.  I *think* I've accounted for most of the possibilities, but open to anything I missed.
Comments/suggestions welcome!
=> util: new XIVAPI CLI query tool

test/unittests/compile_test.ts
This adds a new unit test to mocha to run the `ttsc` compiler and check for compile errors.
This will resolve the issue that came up during the last version bump (see [here](https://github.com/OverlayPlugin/cactbot/actions/runs/7565591888/job/20621874132)), where an earlier PR was successfully merged without any workflow errors during PR checks or merging, but a new TS error appeared in the `release.yml` workflow when `ttsc` attempted to compile and publish the npm package.
Tested locally with `npm test` and also in my fork against both routine and breaking PRs, and confirmed that the `test.yml` workflow is working as expected.
=> ci: add npm compiler test to mocha

util/gen_zone_id_and_info.ts
Closes #47.
I opted for the safer approach of not writing any zone info for an unknown conflict rather than trying to resolve the collision using CFC.  It's strange that this type of conflict (duplicate TTs, tied to the same CFC entry that points back to just one TT) does not show up anywhere else in these data sets, but I don't think it's wise to infer a resolution if this happens again, at least not without investigating it first.  So going forward, no zone id or zone info will be written, but the alert will still appear in the console advising that investigation is needed.
Tested against the 6.55 pre-override data to confirm this will handle this sort of collision correctly, and re-ran the script to make sure there's no impact to existing data.
=> util: fix collision handling in gen_zone script

ui/raidboss/timeline.ts
Closes #58.
Behavior/repro is described in the linked issue, but the cause appears to be that `keepAliveEvents[]` (which contains only those entries which are passed their sync time but have an extended `duration` and are still being shown) is not emptied when `_Stop()` -> `_ClearTimers()` is called after a wipe or jump 0.  As a result, a timeline slot is "reserved" for the defunct keepAlive event on the next timeline start, even though it shouldn't be (and even though nothing is displayed in the ui).  Repeating the repro steps causes `keepAliveEvents[]` to accumulate multiple ghost entries, which is why the timeline continues to shrink each time the bug conditions are satisfied.
`_ClearTimers()` is only called by `_Stop()`, so this shouldn't have any unanticipated side effects. 
=> raidboss: fix shrinking timeline issue

.github/scripts/lint-workflow.cjs, .github/workflows/build-artifact.yml, .github/workflows/css-lint.yml, .github/workflows/javascript-lint.yml, .github/workflows/labels.yaml, .github/workflows/lint-pr-title.yaml, .github/workflows/markdown-lint.yml, .github/workflows/python-lint.yml, .github/workflows/release.yml, .github/workflows/test-sync-files.yml, .github/workflows/test-validate-versions.yml, .github/workflows/update-gh-pages.yml, .github/workflows/update-triggers-branch.yml, .github/workflows/workflow-lint.yml, .yamllint.yml, package.json, requirements.txt
Closes #65 
This adds a linter and corresponding workflow to lint GitHub workflow files.  It has three components:
1. [yamllint](https://pypi.org/project/yamllint/), which handles general YAML syntax lint and some formatting
2. A custom linting script, `.github/scripts/lint_workflow.cjs`, which enforces some specific constraints around workflow file formatting, especially newlines and block ordering.  (I looked for existing tools to provide this functionality but came up empty; newline usage is not governed by YAML schema, so enforcing it is something we'll have to do on our own.)
3. [actionlint](https://github.com/rhysd/actionlint), which provides extensive checking specific to GitHub workflow scripts, including things like semantic errors, shellcheck, dependency checking, etc.
This also …
=> ci: add workflow linter

package-lock.json, package.json, plugin/CactbotEventSource/Properties/AssemblyInfo.cs, plugin/CactbotOverlay/Properties/AssemblyInfo.cs
As mentioned in Discord.  It's been ~6 weeks since last release, and there's been at least one user-facing timeline bug and a number of i18n PRs that would be good to release.
=> build: Bump version to 0.31.3

.github/workflows/label-pr.yml
Small fix for the PR labeling workflow.  It appears that the job that's supposed to run when a PR review is submitted [isn't removing the needs-review label](https://github.com/OverlayPlugin/cactbot/actions/runs/8132959713/job/22223972723) because it relies on a different GH event (`pull_request_review`) than the other jobs (`pull_request_target`), and therefore doesn't auto-inherit read/write permissions on PRs.  Didn't pick this up in testing because it's affected by whether the PR originates from the same repo or a fork.
This is hopefully the easy fix, but the [doc](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) on maximum token permissions seems inconsistent with the [doc](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github- …
=> ci: fix permissions issue in label-pr workflow

ui/raidboss/emulator/data/CombatantTracker.ts
In some extremely rare cases, if the first log line of a split encounter is memory-generated instead of network-generated, and the user's system clock skews later than the server timestamp, and the first network line arrives before that skew offset has elapsed, the first timestamp detection for `CombatantTracker` will not have the correct timestamp.
This causes the forward assignment of "known first-state values" in `addCombatantFromSourceLine` to target the wrong initial state, which breaks player detection.
Sort the timestamps and get an actual first and last timestamp value that's guaranteed to be correct.
=> raidemulator: Fix bug with first/last timestamp detection

.github/scripts/pr-review.cjs, .github/workflows/label-pr-review.yml, .github/workflows/label-pr.yml, .github/workflows/lint-pr-title.yaml
#77 didn't quite do it, but this one should.  Tested against PRs from a forked repo, and it now works fine.
It's a little hacky in terms of a fix, but the reasons (and steps) are explained in a comment at the top of `label-pr-review.yml`.
=> ci: fix perms issue in label-pr workflow (round 2)

util/logtools/splitter.ts
Proposing to add some of the new OP log lines to the log splitter analysis function, specifically:
- `NpcYell` (266) & `BattleTalk2` (267) - possibly useful for identifying phase jumps or mechanics
- `ActorSetPos` (271) - useful for identifying combatant movement associated with a mechanic (esp. with forthcoming changes to `LineCombatant`)
- `SpawnNpcExtra` (272) - initial tether/animation states for combatants
- `ActorControlExtra` (273)  animation changes (although probably revisit this if high-volume categories are added later)
`ActorSetPos` is the most "spammy" -- although I think that's probably also fight-dependant -- so open to excluding it.  But since we already exclude `CombatantMemory` (much more "spammy"), it seems like adding something here would be good, or we'll otherwise …
=> util: add new OP lines to log splitter

ui/raidboss/data/03-hw/alliance/dun_scaith.ts, ui/raidboss/data/03-hw/dungeon/gubal_library_hard.txt, ui/raidboss/data/03-hw/pvp/shatter.ts, ui/raidboss/data/03-hw/raid/a11s.ts
Some comments in-line.  @JLGarber - tagging you since you did the initial Gubal Hard timeline.  I really wanted to get rid of those `GameLog` syncs, so I took a look back at the [discussion you had on the original PR](https://github.com/quisquous/cactbot/pull/693#discussion_r339324028), and I think this is the right implementation of the alternative (at least, it works, so 🤷 ).
=> raidboss: replace GameLog lines (HW)

resources/netlog_defs.ts, util/logtools/split_log.ts, util/logtools/splitter.css, util/logtools/splitter.html, util/logtools/splitter.ts, util/logtools/web_splitter.ts
Adds an "Export Entire Log" button to the web splitter.  It will be disabled if a particular fight is selected (essentially, it will toggle states with the "Export Selected" button), and will otherwise be enabled only if either "Anonymize Log" or "Filter Log for Analysis" is checked (since without one of those, it would just dump the entire file, unmodified, back to the user which is rather pointless).
Also cleans up a couple of the `canAnonymize` properties in `netlog_defs`.
Ref #96 - this is necessary to allow a full log file to be anonymized and exported (without being split), in case the splitter is not properly detecting encounters.
=> util: add export-all option to web splitter

.github/scripts/pr-review.cjs
GH apparently fires a `pull_request_review` event on comments/replies to existing reviews and treats each as a new review (via the `reviews` endpoint).  This fixes an edge case where the `needs-review` tag is incorrectly removed when there has been an unreviewed commit submitted, but a comment/reply to an earlier review is posted after the commit.
(I am rapidly developing an "appreciation" 🙄 for the idiosyncrasies of GH workflow/event logic.)
=> ci: fix pr-review handling of review comments

test/helper/test_timeline.ts, ui/raidboss/data/03-hw/trial/sophia-ex.txt, ui/raidboss/data/03-hw/trial/zurvan-ex.txt, ui/raidboss/data/05-shb/alliance/the_puppets_bunker.txt, ui/raidboss/data/05-shb/alliance/the_tower_at_paradigms_breach.txt, ui/raidboss/data/05-shb/dungeon/heroes_gauntlet.txt, ui/raidboss/data/05-shb/eureka/bozjan_southern_front.txt, ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.txt, ui/raidboss/data/05-shb/eureka/zadnor.txt, ui/raidboss/data/05-shb/raid/e11s.txt, ui/raidboss/data/05-shb/raid/e12n.txt, ui/raidboss/data/05-shb/raid/e1n.txt, ui/raidboss/data/05-shb/raid/e1s.txt, ui/raidboss/data/05-shb/raid/e5n.txt, ui/raidboss/data/05-shb/raid/e7n.txt, ui/raidboss/data/05-shb/trial/wol-ex.txt, ui/raidboss/data/06-ew/dungeon/alzadaals_legacy.txt, ui/raidboss/data/06-ew/dungeon/mount_rokkon.txt, ui/raidboss/data/06-ew/dungeon/the_aitiascope.txt, ui/raidboss/data/06-ew/dungeon/the_lunar_subterrane.txt, ui/raidboss/data/06-ew/dungeon/the_tower_of_babil.txt, ui/raidboss/data/06-ew/raid/p11s.txt, ui/raidboss/data/06-ew/raid/p2n.txt, ui/raidboss/data/06-ew/raid/p3n.txt, ui/raidboss/data/06-ew/trial/golbez-ex.txt, ui/raidboss/data/06-ew/trial/sophia-un.txt, ui/raidboss/data/06-ew/trial/ultima-un.txt, ui/raidboss/data/06-ew/trial/zurvan-un.txt
Addresses @JLGarber 's comment in #106 about linting for "xx.0" float parameters for keyword values in timelines that should just be ints.
(Also fixes an inadvertent bug that was causing a few mis-ordered keywords to not be linted properly.)
Given that this will again touch a decent number of old timelines (although not as many as #106), I've temporarily added a control to limit the lint scope, and this PR only includes changes to EW+ShB timelines (+sophia_ex and zurvan_ex due to sync-files).  Will do follow-on PRs for SB (there are a lot) and ARR+HW before the expac control filter is removed.
=> ci: add check for "point-zero" timeline lint

resources/netlog_defs.ts, resources/netregexes.ts, util/logtools/anonymizer.ts, util/logtools/splitter.ts
This is a start on #94.  The approach I'm taking is outlined there, with one change -- instead of using a separate file (`used_log_types`) to track which line types should pass the filter, this adds relevant props directly to `netlog_defs`, and the splitter parses its ruleset from there.  (I also added some typing enforcement.)  I think this is a better approach, given that we already have a number of props there related to anonymizing.
To help with reviewability, I'm breaking this into three 3 PRs:
1. This one - which adds the filter props to `netlog_defs` and refactors `splitter`.
- `8bb1ee5` is intended to have parity with current functionality, e.g., you should be able to run a log through the live splitter and a local version based on this commit and see exactly the same output. …
=> util: refactor/automate log splitter (1 of 3)

ui/raidboss/emulator/overrides/RaidEmulatorTimeline.ts
This bug is caused by the following:
https://github.com/OverlayPlugin/cactbot/blob/3d9771aebbd4f810fb39fdcc040df7970bfd296a/ui/raidboss/timeline.ts#L411-L413
None of the other `Date.now()` references in `timeline.ts` have an impact for raidemulator due to being overridden already.
This is evidenced by the following debug output from a DSR log file provided in Discord:
=> raidemulator: Fix bug with keepalive timers

resources/netlog_defs.ts, resources/netregexes.ts, resources/regexes.ts, types/net_fields.d.ts, types/net_props.d.ts, ui/raidboss/timeline_parser.ts, util/gen_log_guide.ts, util/logtools/anonymizer.ts, util/logtools/splitter.ts
As mentioned in the TODO in `netlog_defs`, this renames `LogDefinitionTypes`=> `LogDefinitionName`, and `LogDefinitionTypeCode` => `LogDefinitionType` (along with all imports and uses of these types).
This better aligns the type names with the syntax used in `latestLogDefinitions`, e.g. `type` as a numeric line identifier, and `name` as a friendly-name line identifier.
=> resources: rename logdef types

util/gen_zone_id_and_info.ts
Removes extraneous error from missing-translations reports - cn & ko are handled separately in the script.
=> util: ignore missing translations in gen_zone script

.github/logdef_update_pr_template.md, .github/workflows/update_logdefs.yml, package-lock.json, package.json, resources/netlog_defs.ts, ui/raidboss/timeline_parser.ts, util/logtools/web_splitter.ts, util/update_logdefs.ts
Part 2 of the work on #94 (see #109 for more info).
~~This is built on the type-name changes in #127, so that should be merged first (and the changes in `94fd33e` can be ignored, as I will rebase them out before merging).~~
This also sets both `ActorControl` and `NameToggle` to `include: 'never'`.  Both are used ubiquitously in timelines (83 and 60 files, respectively) as wipe regex and to sync --untargetable-- and --targetable-- entries, and since those use cases are handled automatically by timeline tools, I wouldn't think they would have much utility via analysis filtering (although open to leaving them in if others feel differently?).  I'm mostly disabling them from the filter in this PR to avoid massively cluttering the auto-generated PR that will follow.  Speaking of which...
When …
=> util: refactor splitter pt. 2 (auto-updater)

docs/LogGuide.md
- Add overlays to data flow diagram
- Info about cast times
- Info about target counts
- Minor notes
- Replace existing section about action effects
- Update HoT/DoT section
- Talk about buff stacks and overwrites
- Talk about headmarker offsets
- Note about tethers
- Sections about ability resolution, shield %, HP values, and MP as they related to 37/38/39-lines
- Explain 38-lines
- Explain 39-lines
=> docs: Log guide update

test/helper/test_timeline.ts, ui/raidboss/timeline_parser.ts, util/find_missing_timeline_translations.ts, util/logtools/test_timeline.ts
Timeline parsing fails for `CombatantMemory` lines due to the nested nature of the params object. This PR corrects that issue, as well as fixing loading large log files when using `-s` and `-e` parameters.
=> raidboss: Timeline CombatantMemory support

resources/netlog_defs.ts, util/logtools/anonymizer.ts, util/logtools/notifier.ts, util/logtools/splitter.css, util/logtools/web_splitter.ts
Closes #122. I will probably do a separate PR at some point to add support for repeating fields (per the note on `CombatantMemory` in `netlog_defs`).
=> util: anonymizer support for 'possible' playerid fields

resources/netlog_defs.ts, util/logtools/anonymizer.ts
Adds support in anonymizer for repeating fields (e.g. `CombatantMemory`)
=> util: add anonymizer support for repeating fields

ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.txt
~~Depends on #153, will rebase once that's merged.~~
This cleans up and fixes the syncs for the HP %-based pushes in UCOB phase one, by instead detecting the Neurolink puddle drops.
Had to adjust the timeline a bit to allow the sync to work due to the original timeline not having proper phase definitions.
For reference, there are a few objects that get spawned in UCOB that I've seen up to my current prog point:
On zone init / after wipe:
| ID | Description | Count | X | Y (height, not reversed with Z) | Z |
| -- | -- | -- | -- | -- | -- |
| 001E8536 | Unknown | 1 | 0 | 0 | 18 |
| 001EA1A1 | Unknown | 3 | 0 | 0.0171 | 0 |
| 001E850B | Unknown | 1 | 0 | 0 | -20 |
| 001EA1A1 | Unknown | 3 | 0 | 0 | 0 |
During pull:
| ID | Description |
| -- | -- |
| 000006EB | Unknown. Spawns ~8s into pull, …
=> raidboss: UCOB timeline phase sync fixes

util/example_log_lines.ts, util/find_missing_translations.ts, util/gen_log_guide.ts
Closes #157.  I agree with @valarnin 's point there that certain example log lines could benefit from translations.
But since we do not have any translated versions of `LogGuide` at the moment, and the unit tests are all based on the `en` lines, I think it makes sense to at least suppress the warnings for now to prevent clutter on the `missing_translations` pages until it becomes relevant.
=> util: suppress i18n errors for example log lines

plugin/CactbotEventSource/FFXIVProcessIntl.cs
Fixes `kInCombatSignature` & `kJobDataSignature` (matches OP).
Job gauge structs still need to be updated - @MaikoTan, were you looking at those?
=> plugin: 7.0 memory signatures

package-lock.json, package.json, plugin/CactbotEventSource/Properties/AssemblyInfo.cs, plugin/CactbotOverlay/Properties/AssemblyInfo.cs
**This should be merged after #182** 
I think it probably makes sense to get a basic release out with the updated resource files/content list and the mem sig fixes.
=> build: Bump version to 0.32.0

package-lock.json, package.json, plugin/CactbotEventSource/Properties/AssemblyInfo.cs, plugin/CactbotOverlay/Properties/AssemblyInfo.cs
Pushing ex1 support out.  Releasing in draft so the release notes can be edited to (a) note that ex2 is next, followed by other content, and (b) include a link to the content coverage page.  Hopefully this should quell some of the questions in the ACT discord about DT content support...
=> build: Bump version to 0.32.1

util/logtools/fflogs.ts
I mentioned this bug in Discord a few days ago, but `Object.assign` isn't actually duplicating the options properly. This causes issues if the amount of events in a fight exceeds the fflogs page limit.
=> util: Fix bug in fflogs tool

resources/outputs.ts, ui/oopsyraidsy/data/07-dt/trial/zoraal-ja-ex.ts, ui/raidboss/data/07-dt/trial/zoraal-ja-ex.ts, ui/raidboss/data/07-dt/trial/zoraal-ja-ex.txt
This is an initial pass at ex2.  Original timeline thanks to @valarnin (this PR replaces #192), with some adjustments/cleanup from me, but I think the timeline is largely good.
Triggers have been tested against raidemulator but still need some testing in game and may need a little cleanup in some spots (marked as draft/wip for now, but I should be able to get back in tonight).  There's a to-do list at the top for some mechs that do not yet have triggers.  I'm going to keep poking at them tonight, but it may make sense to merge as-is and do with follow-up PRs.
=> raidboss: ex2 timeline+triggers

plugin/CactbotEventSource/CactbotEventSource.cs
During shutdown, the `VisibleChanged` event is raised when the tab with the control is destroyed even if it was never visible. To avoid initialising the control panel during shutdown, I added a check that only initialises the control if it's actually visible. This should fix the crash causing this message:
=> plugin: fix crash during act shutdown

ui/raidboss/data/07-dt/trial/zoraal-ja-ex.ts
This takes care of the remaining to-do for ex2 and does a little cleanup on some things:
* Adds callouts for `Forged Track` (wind/fire + line cleaves) during swords1 & swords2.
* Adds `Chasm of Vollok` (mirrored swords dropping) that happens with no half-room cleave during swords2.
* Adds a longer duration to `Duty's Edge` (multi-hit stack)
* Fixes a potential race condition on some of the collectors that were using `Array.filter` against `data.xx` to reduce pre-existing arrays.
* Some minor naming cleanup.
Tested in the emulator and in-game and works as expected.
=> raidboss: more ex2

ui/jobs/components/drk.ts, ui/jobs/components/index.ts, ui/jobs/constants.ts, ui/jobs/jobs.css
- Merge Blood Weapon and Delirium
- New procbox for Salted Earth
- Since Living Shadow no longer cost Blood gauge, reduce alert threholds
- Adjust Blood gauge alert threholds to 80 and change alert effect (previous from red to bright red, not significant)
=> jobs: DRK DT changes

util/logtools/encounter_tools.ts
Adds Krile, Wuk Lamat, and Koana (Worqor Lar Dor) to the combatant-ignore list in `util/logtools/encounter_tools` as they are now trust dummies or duty support allies (or both).  
NB. Zoraal Ja is also a duty support ally for Worqor Lar Dor, but given that he's decidedly *not* in Everkeep, I've left a to-do to figure out how to handle that.
=> util: add new duty support allies to ignore list

ui/raidboss/data/07-dt/raid/r1n.ts, ui/raidboss/data/07-dt/raid/r1n.txt
There's some TODOs left in the triggers file. I won't have time to look into them probably for the rest of the week at least, I'd rather get what I have up and available.
=> raidboss: Initial R1N

ui/raidboss/data/07-dt/raid/r2n.ts, ui/raidboss/data/07-dt/raid/r2n.txt
I included headmarker info for future savage comparison. 
Loop needs verified still.
Stack/Spread/tank lines/light party stacks  might be better triggered off of headmarkers, felt like the cast ability was slightly slower than headmarker.
`stacks` outputStrings value was copy/pasted from another trigger set, might be better to only include the `en` value and let translators handle the others.
=> raidboss: Initial r2n triggers/timeline

ui/raidboss/data/07-dt/raid/r1n.txt
Add reset based on comments on r2n PR, and add missing initial sync to first raidwide which I missed.
=> raidboss: r1n timeline tweaks

CONTRIBUTING.md, webpack/webpack.config.ts
Small QOL update to allow local webpack instances to access files within the `/user/webpack` directory inside the git root.  This is so user files (resources/sound files, etc.) can be accessed regardless of whether an overlay is pointed to a local plugin install or webpack.
(NB: Although webpack_dev does have access to the /resources dir, that dir is tracked for git updates whereas /user is not.)
=> build: enable user dir access for local webpack instance

resources/netlog_defs.ts, ui/raidboss/data/07-dt/raid/r1n.ts
Right now `R1N Black Cat Crossing` always outputs `Intercards => Cards` regardless of the proper order.  This seems to be happening for two reasons.  The `heading` field for `StartsUsingExtra` line is listed as the `firstUnknownField`, which means it is never being captured by regex.  Second, and unrelated, the output calls in the trigger are inverted.
@valarnin - not sure if there was a reason why the `heading` field was originally treated as optional (e.g. if there is ever a circumstance that field won't be populated from OP), or whether that was just a copy-paste thing?
=> raidboss: fix R1N Black Cat Crossing

resources/outputs.ts, util/logtools/generate_triggers.ts
Example files generated from the tool for ex2 and second expert dungeon:
[example_ex2_console.txt](https://github.com/user-attachments/files/16168928/example_ex2_console.txt)
[example_ex2.ts.txt](https://github.com/user-attachments/files/16171085/example_ex2.ts.txt) (Updated with latest changes as of [c051e13](https://github.com/OverlayPlugin/cactbot/pull/222/commits/c051e130ee5819a8b3c1d6d99476f86d132c5804))
[example_expert2_console.txt](https://github.com/user-attachments/files/16168930/example_expert2_console.txt)
[example_expert2.ts.txt](https://github.com/user-attachments/files/16168931/example_expert2.ts.txt)
This tool will scan all passed log files, scanning for ability-related information, headmarker information, and optionally via flags `MapEffect`, `BattleTalk2`, `NpcYell`, and …
=> [WIP] util: Tool to auto generate basic triggers

ui/jobs/components/blm.ts
At level 84 a trait reduce Manafont cooldown to 100s, before is 120s.
=> jobs: fix Manafont cooldown changed with level

ui/jobs/buff_tracker.ts, ui/jobs/components/nin.ts, ui/jobs/jobs.css
A duplicated `.nin #right-side-icons` here makes right icon position error.
Also find that new Kunai's Bane (TA upgrade) and new Dokumori (mug upgrade) has a longer animation lock for debuff.
=> jobs: NIN right-side-icon fix and TA/dokumori duration fix

ui/raidboss/data/07-dt/raid/r1s.ts
Adds a left/right call for boss. There are multiple spell-ids, could use a double-check to make sure the ones here are both from the boss and not the other entities.
TB callout just calls the initial target.
AoE callout for bloody scratch
=> raidboss: r1s left/right, tb, and aoe triggers

ui/raidboss/data/07-dt/raid/r2s.ts, ui/raidboss/data/07-dt/raid/r2s.txt
Did some testing in zone but not extensive.
=> raidboss: Initial r2s

ui/raidboss/data/07-dt/raid/r1s.ts
This PR adds Japanese translations to the existing R1S triggers.
Please review and let me know if any adjustments are needed.
- Added Japanese translations for `R1S Mouser`
- Added Japanese translations for `R1S Elevate and Eviscerate Launch Self`
- Added Japanese translations for `R1S Elevate and Eviscerate Launch Other`
- Added Japanese translations for `R1S Elevate and Eviscerate Stun Self`
- Added Japanese translations for `R1S Elevate and Eviscerate Stun Other`
- Improved existing Japanese translation for `R1S Splintering Nails` to sound more natural
=> i18n: Add Japanese translations for r1s triggers

ui/raidboss/data/07-dt/raid/r3s.ts, ui/raidboss/data/07-dt/raid/r3s.txt
WIP, completely untested.
Timeline generated via fflogs, which was a bit buggy for the other two fights.
Triggers only tested in raidemulator, and only basic triggers through final fusedown.
=> raidboss: Initial r3s

package-lock.json, package.json, plugin/CactbotEventSource/Properties/AssemblyInfo.cs, plugin/CactbotOverlay/Properties/AssemblyInfo.cs
Prepping this version bump for whoever decides that it's a good time to push what we have for savage out.
Summary includes floor 3 under the assumption #296 will be merged before this.
=> build: Bump version to 0.32.5

ui/jobs/bars.ts, ui/jobs/components/ast.ts, ui/jobs/components/brd.ts, ui/jobs/components/dnc.ts, ui/jobs/components/drg.ts, ui/jobs/components/drk.ts, ui/jobs/components/gnb.ts, ui/jobs/components/mch.ts, ui/jobs/components/mnk.ts, ui/jobs/components/nin.ts, ui/jobs/components/pld.ts, ui/jobs/components/rdm.ts, ui/jobs/components/rpr.ts, ui/jobs/components/sam.ts, ui/jobs/components/sch.ts, ui/jobs/components/sge.ts, ui/jobs/components/smn.ts, ui/jobs/components/war.ts, ui/jobs/components/whm.ts
https://github.com/OverlayPlugin/cactbot/blob/1be5017fe1233268ab6dd10cf8d206f2921508c7/resources/timerbox.ts#L488
The valuescale setting seems to be used as a divider before showing the timerbox text (i.e the remaining time), so translate the plain time to be how many GCDs remaining if we set it to the current GCD length.
But it looks like most of the time, instead of seeing the text, we are just watching the box showing larger -> prepare to press the corresponding button. @Echoring would explain it more!
=> jobs: remove valuescale setting

ui/raidboss/data/07-dt/raid/r3s.ts
This PR adds Japanese translations for the new triggers introduced in #309.
- Add Japanese translation for `R3S Octoboom Bombarian Special`
- Add Japanese translation for `R3S Quadroboom Bombarian Special`
=> i18n: Add Japanese translations for R3S new triggers

resources/netlog_defs.ts, util/logtools/anonymizer.ts, util/logtools/splitter.ts
On more recent versions of NodeJS, it will complain about using a named import from lodash (specifically, `isEqual` which is used in splitter & anonymizer for typeguards) because it is a CommonJS module.  This fix allows `split_log` to be run from the CLI (which is currently broken).
This also updates the logdef for 0x1B lines.  In R4S, one of the uncaptured params contains a duplicate of the actorId, which causes anonymizer to throw uncaught-player errors.  This adds that field as a `possiblePlayerId`, meaning it will be silently anonymized if present but not included as a regex capture group.
=> util: splitter/anonymizer fix

ui/jobs/buff_tracker.ts, user/jobs-example.js
bigbuffs are re-sort by bonus order:
1. devilment (20% crit + 20% DH = 15%+)
2. potion (8%+)
3. 6% damage buffs (balance/spear/divination/finale)
4. 10% crit buffs (litany/chain, 5%+ at about 3000 crit)
5. 5% damage buffs (Dokumori/embolden/technicalFinish/starrymuse/brotherhood/searingLight)
6. 20% DH buff (battlevoice, 4%+ at about 2000 DH)
7. 3% damage buffs (arcaneCircle)
8. standardFinish (5%, mainly always on you)
9. BLU 5% buffs (Attenuations/offguard/peculiar, rarely played with other jobs)
Also remove some no longer used and unnecessary 6.X bigbuffs.
=> jobs: re-sort buff tracker

ui/raidboss/data/07-dt/raid/r4s.ts
This adds some additional info to the callouts for EE2.  One strat involves switching partners based on long vs. short debuff assignment if it's Four Star + Sidewise Spark after; another strat involves fixed positions (and variable partners) based on role & Witchgleam stack count.  This supports both by:
- Adding the list of other players with the same (short vs. long) debuff to the initial call, similiar to the snake callouts in p8s.
- Adding `(X stacks after)` to the Star + Sidewise Spark alert for long debuffs.
=> raidboss: r4s electrope edge 2 improvements

resources/netlog_defs.ts
Fixes #327
Fixes #328 
Changed capture regex does not reference the new fields unless they're required for the trigger. If the new fields are required for a trigger to be handled, the new fields can be included as parameters with wildcard matches, but those triggers will not work for KR/CN users.
=> raidboss: Fix issue with KR/CN compatibility

ui/raidboss/emulator/data/RaidEmulator.ts
This is the cause of raidemulator not seeking to the start of the fight properly when going from a newer encounter to an older encounter.
Basically, the previous encounter's timestamp was held when changing encounters, which causes the initial perspective selection to seek to that timestamp. If the previous encounter was before the new encounter, that's not a big problem since the seek would be capped to the start of the encounter.
But if the previous encounter's timestamp was later than the current encounter, the seek would succeed and be past the end of the newly loaded encounter.
=> raidemulator: Fix bug with double seek in raidemulator

ui/raidboss/data/07-dt/raid/r2s.ts
The party stack head marker appears on multiple players, and pops at the
same time. This produces a much louder sound than usual due to the
sounds overlapping. There's no reason to tell the player about the
stacks twice. Avoid this by supressing the trigger after the first one.
=> raidboss: use suppressSeconds to avoid double-callout stacks

ui/raidboss/data/07-dt/raid/r2s.ts
During the 2nd Alarm Pheromones, players get targeted with a head marker
indicating that they will soon have a poison puddle drop on them. The
player needs to notice this, and then take the puddle out to the edge.
Add an alert for this headmarker to warn the player when the puddle is
about to drop on them.
=> raidboss: add r2s alert for dropping puddles

ui/raidboss/data/05-shb/trial/titania-ex.ts
If players fail the water puddle mechanic, Titania spawns an extra add
for each missed puddle. If many puddles fail, this results in several
triggers overlapping producing an extremely loud noise.
Add suppressSeconds to the trigger to prevent multiple callouts from
overlapping.
We could try to collect the data and call out how many were spawned, but
I think players can use their eyes.
This is mostly a problem when doing the fight with a low number of
players unsynced. Most of the puddles will fail and all the near
simultaneous overlapped triggers create a loud popping sound.
=> raidboss: suppress multiple extra add callouts in titania

ui/raidboss/data/07-dt/raid/r3s.txt
- knuckle sandwich at 177.8 is 6 hits. added annotation IAW other's in timeline.
- correcting knuckle sandwich at 353.7 to x6 vice x8.
=> raidboss: R3S Updating Knuckle Sandwich timeline

ui/raidboss/data/07-dt/raid/r4s.ts
add R4S Witchgleam Self Tracker reminder
Simply show each witchgleam you got
=> raidboss: add R4S Witchgleam Self Tracker reminder

ui/raidboss/data/07-dt/raid/r3s.ts
Removed the phase check on `R3S Murderous Mist` as the later instance of this ability has a different ID.
I was only able to verify the `'9AEA', '9AEB'` IDs for Lariat Combo via VOD, because FF14 RNG is like that. I had a single pull that saw `9AE8` but that pull wiped before the second lariat so I couldn't verify the safe spots. (More FF14 RNG fun: Every single pull that got to this point in the fight, checking the VODs, had the boss jump to south. Except one pull where the boss jumped east. I didn't even realize the boss could jump somewhere else until I was reviewing the VODs.)
For TT1/TT2, there are separate IDs for TT1 vs TT2. I was able to verify all four IDs against VODs.
=> raidboss: R3S Tag Team 1/2, KB towers 2 lariat combo

ui/raidboss/data/07-dt/raid/r2s.ts
During Beat 2, players either start with zero or one heart. A lot of
mechanics happen in sequence, with players getting different mechanics
depending on how many hearts they started with.
First, players who start with 0 hearts get either:
1) stack markers which will grant 4 hearts spread out over everyone in
the stack when it expires.
OR
2) repeatably targetted with puddle aoes they need to bait and drop.
Following this, players with 1 heart either:
1) get a spread marker which they need to move away from other players
OR
2) must grab a tower that spawns at the same time as the spread marker.
The spread markers appear later, around the end of when the baited
puddles and stack markers finish. Typically players with 1 heart stack
in the same spot away from the puddle/stack markers. …
=> raidboss: call tower or spread during beat 2

ui/raidboss/data/07-dt/raid/r2s.ts
The cone tankbuster during r2s appears on both tanks. This results in
the callout for the tankbuster triggering twice, with an overlapping
sound effect and multiple messages on screen.
Setting suppressSeconds would resolve the multiple callouts, but
prevents correctly calling out "tank cleave on YOU".
All of the tank buster cleaves happen simultaneously. Add a collector
trigger to collect the targets of the tank buster. Add delaySeconds to
the tankbuster trigger to give time for the collector to execute.
Replace the check against the target with a check on whether the
collected targets includes the active player. This ensures that the
correct message is displayed, and prevents the overlapping of
simultaneous triggers.
I chose not to add a check on the size of the laser collect, as this …
=> raidboss: avoid multiple callouts during r2s cone tankbuster

ui/raidboss/data/07-dt/raid/r4s.ts
There are two situations for the Bewitching flightwhere where the missing one is supplemented
=> raidboss: add bewitching flight cast id

resources/outputs.ts, ui/raidboss/data/07-dt/raid/r2s.ts
Finally getting around to PRing some additional triggers:
* Revises the 'Stored: ' partner/spread call to an `infoText` and suppresses it for the first two occurrences (since Tempting Twist/Honey Beeline happen immediately after).
* Adds an `infoText` with the subsequent positioning + partner/spread at the beginning of Tempting Twist and Honey Beeline, followed by an explicit `alertText` with that info when the first part of the mechanic resolves.
* Lists some possible TODOs for beat1 & beat2.
* Adds defamation/in/towers calls during beat3.  (NB: I had this mostly worked up before #349, but if people prefer that approach + some added handling for defamations, I can remove it from this PR before merging.)
* Adds callouts for "curtain call" (aka Beeloved Venom).  On this, I added a 'Marge …
=> raidboss: Additional M/R2S triggers

ui/raidboss/data/07-dt/raid/r4s.ts
Fixes #361.
The issue occurs because in some (but apparently not all) logs, the `ActorSetPos` and `ActorControlExtra` packets that are needed to identify the jumping clone and its position are ordered differently.  Adding a short delay to `R4S Sunrise Sabbath Jumping Clone Collect 1` (to ensure the related `ActorSetPos` collector processes first) seems to fix the issue -- and because both collectors happen ~3s before the cannon color collect and subsequent callout trigger, this added delay doesn't delay the mechanic callout at all.
This fixes the issue in the log @valarnin passed along, but additional in-game validation couldn't hurt.
=> raidboss: r4s sunrise sabbath fix

ui/raidboss/data/07-dt/raid/r1s.ts
Currently,the direction of the quad cross clones is incorrect. I think this was a slight oversight by Valarnin when coding. When determining quad cross, the position of `quadCross` should be used for judgment, not `oneTwoPaw`.
=> raidboss: fix R1S stored quad leaps

package-lock.json, package.json, plugin/CactbotEventSource/Properties/AssemblyInfo.cs, plugin/CactbotOverlay/Properties/AssemblyInfo.cs
Would like to get a version bump out asap to address the m/r4s i18n issues being reported in discord -- namely, that #334 hasn't made it into a release yet, so triggers aren't working for non-`en` parsing languages.
Releasing in draft so the release notes can be edited before publication, primarily so the release header can be adjusted based on the final PR merge list (esp. if #360 is merged).
(Closes #368).
=> build: Bump version to 0.32.7

util/logtools/encounter_tools.ts
Fixes a long-standing bug in `encounter_tools`, where the regex'd zoneId is not properly converted from hex to int.  This has been causing `make_timeline` to mis-identify the zoneId in the header of the console output.
(Very low impact bug, but I'm working on some timelines today and I've noticed this before, so just cleaning it up.)
=> util: fix id bug in encounter tools

ui/oopsyraidsy/data/07-dt/dungeon/strayborough-deadwalk.ts, ui/raidboss/data/07-dt/dungeon/strayborough-deadwalk.ts, ui/raidboss/data/07-dt/dungeon/strayborough-deadwalk.txt
Should be largely self-explanatory. Oopsy has not been tested in-game.
I'm not sure what we really want to do about boss 1. It's very much "use your eyes" and not a lot of value from triggers.
Boss 2 we could probably map out the patterns based on that one infographic going around, but that's a lot of extra work, and I kind of want to get the timelines/oopsy in place for now so people have it available.
=> raidboss: Initial Deadwalk package

resources/netlog_defs.ts
Small fix to the log splitter's analysis filter, based on something I noticed while doing the A-rank triggers yesterday.  Right now, the analysis filter does not include `GainsEffect`/`LosesEffect` lines that originate from an NPC (4.{7}) that are applied to an NPC, e.g., self-applied boss status effects.  This PR fixes that.
Extremely small overall impact to the number of lines that pass the filter, but they are important ones.
=> resources: add NPC-source+target effects to analysis filter

ui/raidboss/data/07-dt/hunts/heritage_found.ts, ui/raidboss/data/07-dt/hunts/kozamauka.ts, ui/raidboss/data/07-dt/hunts/living_memory.ts, ui/raidboss/data/07-dt/hunts/shaaloani.ts, ui/raidboss/data/07-dt/hunts/urqopacha.ts, ui/raidboss/data/07-dt/hunts/yaktel.ts
- I couldn't find the script, so this is done manually.
- Not sure if the German part of 'Kirlirger the Abhorrent' is correct.
- Not sure if the escape characters are handled correctly.
=> i18n: replace sync for dt hunts

package-lock.json, package.json, plugin/CactbotEventSource/Properties/AssemblyInfo.cs, plugin/CactbotOverlay/Properties/AssemblyInfo.cs
If #386 is ready before the servers come up, that could be included as well.
includes:
- more Savage
- Strayborough Deadwalk
- Worqor Lar Dor normal
- A-rank Hunts
- more i18n
=> build: release bump 0.32.8

ui/raidboss/data/07-dt/dungeon/strayborough-deadwalk.ts
Träumerei's Malicious Mist also applies a 12s bleed.
=> raidboss: Deadwalk Träumerei Malicious Mist output change

ui/raidboss/data/06-ew/alliance/aglaia.ts
Seems that this typo has been there since the initial trigger set was added in quisquous/cactbot#4276.
=> raidboss: fix cast ID for Aglaia Double Immolation

ui/raidboss/data/07-dt/hunts/urqopacha.ts
There's some weird gaps and sequencing in the ability ids used for the Honor's Accord/Dishonor's Accord-based attacks.  But all were verified across nearly a dozen logged kills, and all were copied/pasted directly from logs -- so no typos, I promise.
=> raidboss: add Kirlirger (S-rank: Urqopacha)

package-lock.json, package.json, plugin/CactbotEventSource/Properties/AssemblyInfo.cs, plugin/CactbotOverlay/Properties/AssemblyInfo.cs
Primarily to pick up the Alexandria fix for non-EN players.
includes:
- #395 
- #391 
- #396 
- #397 
- #398 
- #400 
- #399 
- #401 
- #403 
- #404 
- #405 
- #406 
- #408 
- #409 (tentative)
=> build: Version bump to 0.32.9

ui/raidboss/data/07-dt/hunts/heritage_found.ts
#409 mistakenly edited the `en` strings for these callouts -- this reverts the `en` strings back to what they were previously. 
@Akurosia - could you please double-check and confirm that `Start` in the `de` strings is correct and doesn't need translation?
@mooondark - you also have the `für` in #411 - I think that might need to be changed for `fr`?
=> raidboss: fix mistaken translation edit to Atticus

ui/raidboss/emulator/data/LogEventHandler.ts
Noticed this while working on the hunt marks, but raid emulator incorrectly detects the zone information for overworld hunt marks -- it will always assign the encounter to the zone you change to after the encounter ends.
This should fix the issue.  And testing a mix of overworld/instance content logs from the last week shows zone info being correctly detected.  (Related: there also seems to be an issue with correct party detection in overworld content, but I'll look into that later.)
=> raidemulator: fix overworld combat incorrect zone detection

ui/raidboss/data/07-dt/hunts/heritage_found.ts, ui/raidboss/data/07-dt/hunts/yaktel.ts
Fix "Start" to "Starte" for a more natural sounding.
Fix tripple "Sammmeln" to "Sammeln
=> i18n: small translation fixes

docs/RaidbossGuide.md, types/trigger.d.ts, ui/raidboss/data/00-misc/test.ts, ui/raidboss/popup-text.ts
Something that's been lingering on my to do list for a while, but some of the conversations on PRs today made me finally get to it.  This adds an optional trigger property `countdownSeconds:`, which supports either a number or a `(data, matches) =>` function.  If specified, it will append a live countdown (floating point, tenths place) to any popup text generated by that trigger.  (As currently written, the countdown portion of the text will not be output via tts, because that gets pretty messy.)
I added a demo of this to the countdown start trigger in Summerford Farms, so this can be easily tested with the usual `/cd 5` there.
The only significant judgment call (which I'm very open to revisiting) was how to handle potential interactions between `countdownSeconds` and `durationSeconds` …
=> raidboss: add support for live countdowns

ui/oopsyraidsy/buff_map.ts
The `diff` appears larger here than it really is because I reordered the buffs by role and added headings where appropriate to bring some order to the chaos.  
* `68fa295` and `b7b8fd3` are the re-ordering commits (with some added comments), but shouldn't have any substantive changes.
* The remainder are commits with individual buff changes.
=> oopsy: update buff map with DT/7.0 changes

ui/raidboss/data/07-dt/raid/r4n.ts
Currently, the callout for XFold Blast accumulates and then calls out
the chain of N/S one time near the start of the mechanic.
This works ok, but it can be easy to get lost in the middle and lose
track of whether and when you should swap.
To handle this, detect when the previous XFold Blast hits, and call out
the next platform direction. To help aid in recall if you need to swap
or stay, keep track and call out the direction with an alert level when
you need to swap, and an info level when you need to stay.
=> raidboss: add callout to swap or stay during XFold Blast

ui/oopsyraidsy/data/00-misc/general.ts, ui/oopsyraidsy/oopsy_options.ts
Shows a ⚠️ warning when a party damage cooldown (e.g., Chain Stratagem, Battle Litany, etc.) is overwritten.  Also adds some missing BLU mitigation overwrite warnings.
=> oopsy: add support for tracking overwritten party damage CDs

util/find_missing_timeline_translations.ts
In the spirit of dealing with pesky persistent TS compiler warnings, this adds an explicit null check in find_missing_translations.  
(Gotta love historical JS quirks like 'null' having the same type tag as objects...)
=> util: fix null check in find_missing_translations

ui/raidboss/emulator/overrides/RaidEmulatorPopupText.ts
This fixes a pesky TS compiler warning about doing a number comparison before the type is constrained:
=> raidemulator: re-order validation checks for delay prop

ui/raidboss/data/07-dt/trial/zoraal-ja-ex.ts
Cleaning up a (::cough::) stray error message I left in Forged Track that was never intended as a trigger output, and also fixed the race condition issue that was occasionally causing it to fire (along with slightly improved error logging.)
=> raidboss: fix race condition in EverkeepEx Forged Track

ui/raidboss/data/07-dt/trial/valigarmanda.txt
There apparently is an HP-based phase push (value unknown) out of the opener directly to the first Skyruin.  This adds a couple of windows to properly detect that.  (Tested in-game).
=> raidboss: fix bug in Vali normal timeline

docs/OopsyraidsyGuide.md, ui/oopsyraidsy/damage_tracker.ts, ui/oopsyraidsy/oopsy_viewer.ts
Fixes an old issue with `oopsy_viewer` where replayed logs did not correctly implement `delaySeconds` and `suppressSeconds` properties on triggers.  (Tested & verified fixes with some WIP triggers and other improvements I'm working on.)
=> oopsy: fix oopsy_viewer to support delay/suppress properties

ui/raidboss/data/07-dt/raid/r4s.ts
After mustard bomb goes off, the tanks need to transfer a debuff to one
of the players who was not hit by kindling cauldron. Currently we just
call out "pass debuff".
We already have the data required to determine who is safe to pass the
debuff to. Filter the list of party names to and include the shortened
names of the players who its safe to pass to.
=> raidboss: include safe players when calling pass debuff

ui/raidboss/data/07-dt/raid/r4s.ts
Changes M4S Left/Right Roll calls to be consistent with M4N (uses `<= Get Left/West` and `Get Right/East =>` instead of just `Left` and `Right`).
=> raidboss: update Left/Right Roll calls for consistency

ui/raidboss/popup-text.ts
As discussed in #458 and #464.
Right now, tts will strip an arrow (`<=`, `<-`, `=>`, or `->`) at the beginning or end of an output string so it does not get spoken.  Arrows in the middle of a string are spoken as `then` (translated as needed).
This allows the beginning/end arrows to be variable length (e.g., `<==` or `<---`) and still be stripped, so we don't end up with partial substitution weirdness (e.g., tts speaking `equals` when `<==` is stripped to `=`).
=> raidboss: variable-length arrow substitution in tts

resources/outputs.ts, ui/oopsyraidsy/data/07-dt/trial/zoraal-ja.ts, ui/raidboss/data/07-dt/trial/zoraal-ja.ts, ui/raidboss/data/07-dt/trial/zoraal-ja.txt
Tested in emulator and in game.
This re-uses a lot of the tile calculation logic I did for EverkeepEx, but determining/calling safe spots is handled a little differently because the forged track patterns are both fixed and simpler.  For calling Forged Track, it will call a single inner safe tile regardless of how many tiles are actually safe, with priority given to the inner N/S tiles.  I *think* this probably fine, but given the recent discussion on #429 & #431, I wanted to mention that.  If folks prefer a different priority order, feel free to PR a config option, but I think this is fine for an initial pass at least.
=> raidboss/oopsy: add Everkeep (normal) package

ui/oopsyraidsy/damage_tracker.ts, ui/oopsyraidsy/player_state_tracker.ts
Closes #467.
This fixes the extraneous '???' entry that was showing up in oopsy mistake reporting.  The fix to party list handling in #447 ensures that the current player's id will always be in the party list.  However, oopsy's identification of the current player can come from `onPlayerChangedEvent` as well as `ChangePrimaryPlayer` lines, and in the former case, the player id was in lowercase, causing an extraneous entry in the player list when the current player was then (re-)added (in uppercase) from `PartyList`/`AddCombatant` lines.  This PR ensures that the current player id will always be in uppercase (and does so in several places to future-proof `PlayerStateTracker` and `DamageTracker` if those classes get used elsewhere later).
Massive thanks to @xiashtra who did the debugging, …
=> oopsy: fix lower-case player id

test/helper/test_trigger.ts, ui/raidboss/data/05-shb/ultimate/the_epic_of_alexander.ts
Per comment in #469 and discussion/fix in #465, this adds a unit test for mid-string long arrows (e.g. <--, ==+, etc.), as tts will not translate mid-string long arrows correctly.
(Running the unit test picked up a handful of mid-string long arrows in the TEA Wormhole trigger `cn` output strings, which are now fixed.)
=> test: add unit test for mid-sring long arrows

ui/raidboss/data/07-dt/raid/r4s.ts
This PR detects safe spots for Twilight Sabbath earlier, and combines the bait trigger with the first safe direction trigger.
This one goes out to people with high latency or inconsistent ping, who don't have enough time to react to the safe direction trigger that currently exists.
Only tested in RaidEmulator so far, will test in-game during reclears on Tuesday (unless someone else can test before then).
Current triggers:
New triggers:
=> raidboss: Tweak Twilight Sabbath triggers

ui/raidboss/data/07-dt/raid/r4n.ts
Valarnin recently did some work to improve the Twilight Sabbath triggers
in m4s. He discovered that we can detect the Wicked Replica cleave
directions using the ActorControlExtra log lines with the 0197
'PlayActionTimeline' category.
Do the same in m4n, replacing the check for CombatantMemory trigger.
This should be more precise and less overhead. It is also slightly less
code.
As far as I can tell, all the clones use the same 11D6 and1 11D8 values
for their left or right cleave.
=> raidboss: use ActorControlExtra for sidewise spark cleaves

ui/raidboss/data/07-dt/raid/r4s.ts
This series includes several strategy options for the m4s fight that fit the
standard NA PF strategies.
- **raidboss: add support for DN strategy for Ion Cluster in m4s**
- **raidboss: add support for DN strategy during Witch Hunt in m4s**
- **raidboss: add uptime sunrise sabaath callouts in m4s**
These are based off the shabin pastebin and hector guide, with the uptime
waymarks strategy for sunrise sabaath.
I made all of these configuration options, so that existing default callouts
which do not use a specific strategy are not affected. I tried to put good
brief explanations, and used the standard strat names I see going around.
I've tested variations of this code in my runs, though it did not use a
strategy option at the time. Thus, this exact code is not yet battle tested
outside of …
=> raidboss: r4s strategy options for NA strats

resources/content_list.ts, resources/content_type.ts, ui/dps/dps_common.js, ui/oopsyraidsy/oopsy_options.ts, util/logtools/encounter_tools.ts, util/zone_overrides.ts
- Remove no longer needed synthetic content type for The Masked Carnivale (ref: #494)
- Re-run resource file generation scripts
- Add new content entries to `content_list.ts`
- Add entries for additional content types to relevant scripts
=> resources: 7.1 resources cleanup

plugin/CactbotEventSource/FFXIVProcessIntl.cs
(probably, `shieldPercentage` should be merged into `CharacterDetails` as it's in the same internal struct in the game, but that's beyond the scope of this PR)
Fix offsets for EntityMemory for patch 7.1
Job sigs and offsets seem fine. Not sure if any jobs had actual job gauge data layout changes this patch, if so they can be fixed with a separate PR.
=> plugin: Fix offsets for global 7.1

ui/raidboss/data/07-dt/trial/queen-eternal-ex.txt
Small thing I caught when testing this a sec ago, just need to suppress the `--sync--`s
=> raidboss: ex3 timeline fix

ui/raidboss/data/07-dt/ultimate/futures_rewritten.ts, ui/raidboss/data/07-dt/ultimate/futures_rewritten.txt
Untested in-game, but `test_timeline` passes More Than Twenty-Five pulls from my logs tonight, so it's probably good enough structurally. Definitely need some criticism on whether it's too cluttered or not cluttered enough, as well as basic sanity checking given I finished this after 2 AM.
=> raidboss: FRU initial P1 timeline

ui/raidboss/data/07-dt/ultimate/futures_rewritten.ts
This is partially based on an experimental set of triggers @valarnin tossed in the ACT Discord server yesterday or the day before. I wasn't able to get the Blasting Zone safe area triggers working, but apart from that and the tank buster trigger, everything in here is stuff I was able to test tonight and confirm as working. The timing for delays and durations is all stuff that fits relatively closely to match mechanics. (Castbars in phase 1 are a little longer than we're used to.)
=> raidboss: Basic FRU P1 triggers

plugin/CactbotEventSource/FFXIVProcessKo.cs
This is the 1st of PRs for the Korean client 7.0, which will be updated on December 3rd.
Maintenance: [2024-12-02 12:00](https://www.timeanddate.com/worldclock/converter.html?iso=20241202T030000&p1=235&p2=137&p3=64&p4=263&p5=195&p6=37&p7=33&p8=248) ~ [2024-12-03 18:00](https://www.timeanddate.com/worldclock/converter.html?iso=20241203T090000&p1=235&p2=137&p3=64&p4=263&p5=195&p6=37&p7=33&p8=248) (KST, 30 hours) 
- 1st (Here) https://github.com/OverlayPlugin/cactbot/pull/523
- 2nd https://github.com/OverlayPlugin/cactbot/pull/524
- 3rd https://github.com/OverlayPlugin/cactbot/pull/525
---
- Update plugin/CactbotEventSource/FFXIVProcessKo.cs
- This is a copy of [PR #436](https://github.com/OverlayPlugin/cactbot/pull/436), cn 7.0.
=> plugin: ko 7.0 signatures and memory

ui/raidboss/timeline_parser.ts
Noticed a minor bug with `TimelineParser.Translate`. The opening/closing curly braces were being duplicated. This is visible in the output from `translate_timeline` and in the cactbot config UI's timeline editor:
Original timeline entry:
```
14.6 "Cyclonic Break 1 (targeted)" Ability { id: "9CD1", source: "Fatebreaker" }
```
"translated" line before bugfix:
```
14.6 "Cyclonic Break 1 (targeted)" Ability { {"id":"9CD1","source":"Fatebreaker"} }
```
"translated" line after bugfix:
```
14.6 "Cyclonic Break 1 (targeted)" Ability {"id":"9CD1","source":"Fatebreaker"}
```
It wasn't really causing any problems since these translated timelines weren't being re-parsed by anything, but it was bothering me.
=> raidboss: Fix minor bug with `TimelineParser.Translate`

.github/actions/setup-js-env/action.yml
~~Update the typedef for node to v20, and~~ update the action.yml file to use setup-node@v4 which bumps its own dependencies to use node v20.
This fixes a warning during action builds, as well as aligning type hints more correctly with what the internal node types are.
(node v20 was required as of https://github.com/OverlayPlugin/cactbot/commit/4c5cf21e06e024f0133357cbce487c338d0ea960, but for some reason the action wasn't updated at the time)
=> build: Update actions/setup-node to v4

ui/raidboss/data/07-dt/ultimate/futures_rewritten.ts
Some early p2 triggers -- tested in emulator + vod, but hasn't yet been tested in game (although I should be able to tomorrow night unless someone else gets to it first).
=> raidboss: FRU P2 initial triggers

.github/scripts/npm-package.cjs, tsconfig.npm.json
#271 removed some paths from the default tsconfig, which causes issues when building the npm package.
This PR adds an npm package-specific tsconfig file to resolve the issue.
=> build: Fix NPM package creation errors #535

ui/raidboss/data/07-dt/ultimate/futures_rewritten.ts
Per discussion in discord.  There's an intermittent issue with stale position data on `StartsUsing` lines for Icicle Impact; this switches to `StartsUsingExtra`, which resolves the issue.
I'd like to version bump again after this and #537 are merged, as this is a bug fix.
=> raidboss: fix FRU P2 Icicle Impact

ui/raidboss/data/07-dt/ultimate/futures_rewritten.ts, ui/raidboss/data/07-dt/ultimate/futures_rewritten.txt
This has been tested in-game. I adjusted some timings to better match what I saw across my logs to match `test_timeline` and added the remaining `targetable` entries. I also combined the Shining and Frost armor entries since those always go off simultaneously but the order in the log is random. Finally, I filled out some more data on the P2 abilities in the ability list.
Timings for intermission and beyond have not been modified.
=> raidboss: Improvements to FRU P2 timeline

ui/oopsyraidsy/oopsy_summary_list.ts
Also fix the generic `string` type on the array to be properly typed to `OopsyMistakeType`.
=> oopsy: Add `damage` type to oopsy summary table

resources/conditions.ts
Feint also applies to magical damage at reduced efficacy since Endwalker.  I don't think we're using this anywhere anymore, but update it anyways for consistency.
=> resources: Update caresAboutAOE

ui/raidboss/data/00-misc/test.ts, ui/raidboss/data/07-dt/dungeon/vanguard.ts, ui/raidboss/popup-text.ts
This fixes a bug (so far only occurring in Vanguard triggers) where `countdownSeconds` is used in conjunction with `delaySeconds`.  Previously, the countdown end time was set to the trigger execution time + the countdown; however, if a delay is also present, the countdown would then be truncated by the amount of the delay (and would display past 0.0), since the alert duration is the greater of the original countdown value or duration.
Fix tested and confirmed working in Vanguard and with some test triggers.  Behavior now matches repo documentation.
cc: @xiashtra who I think (?) mentioned this issue originally
=> raidboss: fix bug with delays + countdowns

resources/netlog_defs.ts
The analysis filter for `GainsEffect`/`LosesEffect` currently excludes effects applied by `E0000000` to an NPC (`4.{7}`).  This fixes the filter criteria.
NB.  See https://github.com/OverlayPlugin/cactbot/pull/538#discussion_r1912366585 - this was causing the analysis filter to exclude certain relevant lines in FRU, for example, like:
```
30|2025-01-08T22:11:33.4700000-05:00|307|Invincibility|0.00|E0000000||4000684F|Ice Veil|00|2513805||
```
=> resources: tweak GainsEffect/LosesEffect analysis filters

ui/raidboss/emulator/overrides/RaidEmulatorTimelineUI.ts, ui/raidboss/raidemulator.ts
For timeline triggers, alert text / tts was not showing up in raidemulator.
Due to circular dependency in bindTo, a setter was added for popup text.  Suggestions welcome since I am not familiar with typescript / this project
=> raidemulator: Fix trigger popup text not showing up

resources/responses.ts, ui/raidboss/data/07-dt/ultimate/futures_rewritten.ts, ui/raidboss/data/07-dt/ultimate/futures_rewritten.txt
~~This has the rest of p2 and initial p3 through Ultimate Relativity.  I'm marking this as draft/WIP for now because, even though it looks fine in RE, it needs some solid testing in-game (especially on the UR timings).  And there's probably comment typos thanks to my crappy keyboard, and who knows, probably other mistakes too.~~  
(1/11/25 edit: This now has the rest of P2 and P3.  I'll PR the P4 stuff separately.)
I started adding strat options for some stuff as well.  So far:
* Sinbound Holy - the LesBin/current pf strat seems to be to always rotate away from Shiva unless she spawns on a knockback spot, in which case everyone races CW and the group approaching her then slides to rejoin the other before Silence/Stillness.  I haven't seen any other strats getting attention, but defer to …
=> raidboss: FRU - p2 + p3

resources/content_list.ts, ui/raidboss/data/00-misc/test.ts, ui/raidboss/data/04-sb/hunts/yanxia.ts, ui/raidboss/data/05-shb/hunts/amh_araeng.ts, ui/raidboss/data/05-shb/hunts/il_mheg.ts, ui/raidboss/data/05-shb/hunts/kholusia.ts, ui/raidboss/data/05-shb/hunts/lakeland.ts, ui/raidboss/data/05-shb/hunts/ss_rank.ts, ui/raidboss/data/05-shb/hunts/the_raktika_greatwood.ts, ui/raidboss/data/05-shb/hunts/the_tempest.ts, ui/raidboss/data/06-ew/hunts/elpis.ts, ui/raidboss/data/06-ew/hunts/garlemald.ts, ui/raidboss/data/06-ew/hunts/labyrinthos.ts, ui/raidboss/data/06-ew/hunts/mare_lamentorum.ts, ui/raidboss/data/06-ew/hunts/ss_rank.ts, ui/raidboss/data/06-ew/hunts/thavnair.ts, ui/raidboss/data/06-ew/hunts/ultima_thule.ts, ui/raidboss/data/07-dt/hunts/heritage_found.ts, ui/raidboss/data/07-dt/hunts/kozamauka.ts, ui/raidboss/data/07-dt/hunts/living_memory.ts, ui/raidboss/data/07-dt/hunts/shaaloani.ts, ui/raidboss/data/07-dt/hunts/ss_rank.ts, ui/raidboss/data/07-dt/hunts/urqopacha.ts, ui/raidboss/data/07-dt/hunts/yaktel.ts
- added coverage report comments for SS-rank hunt triggers
- added descriptive name for the Cactbot test triggers (will show in the config UI instead of "Middle La Noscea")
- removed Cape Westwind and The Steps of Faith from `content_list.ts` so they no longer show on the coverage report (both instances were re-worked from Trials into solo instances during Endwalker)
=> raidboss: more coverage comments

ui/config/config.ts, util/coverage/coverage.css, util/coverage/coverage.d.ts, util/coverage/coverage.html, util/coverage/coverage.ts, util/gen_coverage_report.ts
Plus dark theme, autodetected based on media query with an optional `?theme=dark|light` query parameter to override. If manually overridden, that setting is saved in local storage and used in the future.
Light theme:
Dark theme:
Dark theme with filtered zone table:
Example of sticky headers on zone table, with row hover effect:
I'm still working out a few minor bugs with table borders, as seen on the last screenshot with the sticky headers, and with the description megaphone icon not floating left properly, but this is code complete otherwise and ready for a general review.
=> util: New zone coverage report format

ui/raidboss/data/06-ew/trial/asura.ts, ui/raidboss/data/06-ew/trial/asura.txt
Had this pop up in duty roulette and noticed some issues.
Typo in Iconography ability IDs, and syncs on lines less than 3 seconds apart without a shortened sync window.
There's another issue where the timeline doesn't have the actual text for the `Iconography` lines, I think due to the text being too long and being a single word?
Maybe this needs a different `replaceText` entry such as the following?
```ts
'Iconography: Pedestal Purge/Wheel Of Deincarnation/Bladewise': 'Purge/Wheel/Bladewise',
```
=> raidboss: Fix issues with asura timeline syncs

ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.ts
Updates the Ifrit initial dash detection to use `ActorSetPos` instead of `CombatantMemory`.
Also adds a trigger for Titan jumps, since it's now possible to detect jump direction with consistency via `ActorMove`.
Posting as Draft/WIP until I can test it in-zone, but looking for feedback on the `TODO` I left in the new trigger.
=> raidboss: UWU ActorSetPos Ifrit update

ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.ts
Based on @valarnin 's original work in #88.  This adds safe direction calls for Titan's jumps.
Tested in game and against a handful of recent pulls in the emulator.
Closes #85 .
=> raidboss: UWU add Titan jumps

util/logtools/generate_triggers.ts, util/xivapi.ts
Updates the xivapi URL for the scripts that generate triggers and generate resource files to use the new `v2` endpoint (replacing the current `beta` endpoint).   Tested & confirmed that no changes needed other than the URL root.
(See https://discord.com/channels/474518001173921794/557164349714726932/1336460108150079488 for more info.)
=> util: update xivapi url

resources/util.ts, ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.ts, ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.txt, ui/raidboss/emulator/EmulatorCommon.ts
Summary of changes thus far:
- Timeline tweaks in P2 so that dynamo/chariot snapshots are visible as timeline entries
- These mechanics are right on the border of "too much" for a normal fight, but given the vast desync between when dynamo/chariot snapshot and when the actual animations happen, I feel that it's worth the extra timeline entries instead of having them collapsed as a duration mechanic as they were before.
- Fix sync issue with a tankbuster in P2
- Fix some sync issues with start of P3
- Change Blackfire Trio's Nael trigger to use ActorSetPos lines, this fixes an occasional issue due to lag as well as cutting down on `getCombatants` calls
- Add config+trigger for finding your tower for Heavensfall knockback
- Update Twintania phase change watcher to use neurolink spawns …
=> raidboss: UCOB cleanup

ui/raidboss/data/07-dt/ultimate/futures_rewritten.ts, ui/raidboss/data/07-dt/ultimate/futures_rewritten.txt
Cleaning up the rest of the fight timeline, including adding p4 enrage + proper syncs for the p5 jump (since it can vary).  Also added various targetable/untargetable lines, and removed a few actor names that were causing sync issues.
There was a lot of creeping drift over the back-half of the fight which resulted in a bit of a cascade of adjustments.  ~~This looks pretty tight now against a handful of kill & wipe logs, although I would like to check in-game and against vod, particularly as the targetable/untargetable lines were based on VOD timestamps and making so many adjustments may have screwed up those timings.  (I also want to re-check the durations on p5 exalines, since that looks strange to me.) Unless someone weighs in sooner, I should be able to make any final adjustments and …
=> raidboss: FRU p4+p5 timeline cleanup

ui/raidboss/data/07-dt/ultimate/futures_rewritten.ts
quick fix for the triggers to respect your settings (DefaultPlayerLabel) instead of enforcing the use of the character's first name, tested it
=> raidboss: fixing names for FRU triggers

docs/RaidbossGuide.md, resources/user_config.ts, ui/config/config.ts, ui/raidboss/raidboss_config.ts
This adds two optional properties to config options, `disabled` and `hidden`, that can access the values of other config options in the config group and programmatically be hidden or disabled as other config options change.  Essentially, this allows the ability to create "child" config options that will only appear or only be modifiable if their "parent" is set a certain way.
I originally had a stronger use case for this with some FRU p4 stuff I was working on, but I figured out an alternative way to do it without needing configs.  I was going to shelve this, but someone in discord recently requested an option to have relative (vs. true) directions called out for P3 Ultimate Relativity, so there is at least a potential use for this now.
Some completely made up mockups below to illustrate: …
=> config: Add capability to disable/hide config options

plugin/CactbotEventSource/FFXIVProcessIntl.cs
Sigs validated and structs otherwise fine.  There could be (probably are?) some changes to the BLM job gauge with the removal of the Astral Fire/Umbral Ice timer, but I don't play BLM so can't address.
(NB: This includes a small bit of cleanup - I changed the offset for `CharacterDetails` (and its fields) to match the layout in aers/FFXIVClientStructs, and `shieldPercentage` was moved into `CharacterDetails` with the correct offset.)
=> plugin: 7.2 struct changes

.eslintrc.cjs, docs/RaidbossGuide.md, eslint/cactbot-party-member-property-access.js, ui/raidboss/data/07-dt/raid/r2s.ts, ui/raidboss/data/07-dt/raid/r4s.ts, ui/raidboss/data/07-dt/trial/zoraal-ja.ts, ui/raidboss/data/07-dt/ultimate/futures_rewritten.ts
Adds lint rule and doc update to prevent use of `data.party.member().nick` or `.toString()` in raidboss triggers.  Also lints some current uses of the same in recent trigger files.
Closes #625.
=> lint: prevent prop use on data.party.member

util/gen_zone_id_and_info.ts
Updating the `gen_zone_id_and_info` script to reflect underlying xivapi schema changes for the `TerritoryType` sheet.
(No actual resource file changes with 7.2hf1 though.)
=> util: fix weather rate schema in gen_zone_info

ui/raidboss/data/07-dt/raid/r5n.ts, ui/raidboss/data/07-dt/raid/r6n.ts
These split busters are self-targeted casts from the boss; update the triggers to use headmarkers instead.
=> raidboss: update M5N/M6N tankbusters

ui/raidboss/data/07-dt/raid/r5s.ts
Near the middle of the fight, a bit before the second arcady fever, the
boss does one more X-snap Twist & Drop the Needle. This does not
currently have a callout.
Based on my log files, this is due to missing IDs in the snapTwistIdMap,
ranging from A4DB to A4E0. I initially analyzed the log files I have to
determine that these are ordered from 2 to 4 in pairs. I also noticed
that "west" IDs typically come first before "east" IDs. I verified the
snap counts by lining them up in the log file with the "Dancing Green
readies" log lines. I also tested in game and confirmed that the
east/west values match in practice.
=> raidboss: r5s: add missing X-snap Twist IDs

ui/raidboss/data/05-shb/eureka/delubrum_reginae_savage.ts
Closes #609
This could be added to the non-savage as well, but less likely to trigger there as the risk of dying is less and explanations for mechanics not as needed.
=> raidboss: add wakeUP trigger to DRS

resources/netregexes.ts, util/logtools/encounter_tools.ts, util/logtools/make_timeline.ts
Add support to make_timeline to automatically replace RSVData-obfuscated entries with their deobfuscated equivalents when that information is available in the log file.
Also some tweaks to the logic for matching start/end line timestamps, because I had an instance of "end timestamp matched before start timestamp was found" due to it only matching timestamps and me having more than a day's worth of log lines in the same file, with a timestamp overlap across both days.
=> util: make_timeline RSVData support

ui/raidboss/data/07-dt/raid/r5s.ts, ui/raidboss/data/07-dt/raid/r5s.txt
Timeline in this initial part of the PR for review.
Took some liberties with the snap/twist timeline entries, otherwise they'd be even more ugly.
Working on triggers for the Frogtourage cleaves at `454.6`, `458.7`, and `504.5`, but those aren't ready yet, I'll add those to this PR when they're good to go.
=> raidboss: More fifth floor

ui/raidboss/data/07-dt/raid/r6s.ts
Untested in-game. Not sure if this should remove the TODO item for `safe corners for quicksand?` at the top, as this calls the danger corner instead (since there are at least two strats going around for that mechanic).
Pattern numbers should correspond to the patterns on this image, unless I have misassociated them somewhere:
Possible initial cactus spawns (not in pattern # order, these were in the order I encountered them):
```
83.987|116.001
107.517|107.517
89.999|100.009
100.009|89.999
116.001|83.987
116.001|116.001
83.987|108.005
109.989|100.009
92.502|92.502
100.009|83.987
110.996|116.001
83.987|108.005
89.999|100.009
116.001|92.013
110.996|83.987
83.987|116.001
107.517|107.517
100.009|100.009
107.517|92.502
88.992|83.987
```
=> raidboss: Add cactus triggers to m6s

ui/raidboss/data/07-dt/raid/r5s.txt
(Closes #692.)
Untested in-game, but works with `test_timeline` against my logs. I also added a few other safety syncs elsewhere to keep minor lag from intruding.
=> raidboss: Add safety syncs to Arcadion 5 timeline

ui/raidboss/data/07-dt/raid/r8s.ts
Based on my logs, this change will fix the current wrong calls when counterclockwise.
The root of the issue seemed to be that the current trigger iterates through the array incorrectly when counterclockwise. Clockwise iterates 0 => 4, but counterclock requires different iteration method based on the current storing of orders.
This PR uses an integer map of the indices to iterate, cheaper operation than trying to pop and insert.
=> raidboss: r8s champion's circuit counterclockwise fix

ui/raidboss/data/07-dt/trial/queen-eternal-ex.txt
Per complaints from my casual mount farm group.
- "Literally unplayable."
- "How am I supposed to know when I should start hitting the boss again?"
- "`<other memes go here>`"
Also fixed the timeline header to match our newer standard from make_timeline.ts output.
=> raidboss: SpheneEx header fix and targetable line

ui/raidboss/data/07-dt/raid/r8s.ts
- Weal of Stone
https://youtu.be/vvJdDyZD3So?si=DAphfIoXLoEDiHLv&t=792
- Weal of Stone Cardinals
https://youtu.be/vvJdDyZD3So?si=Kc9Zx0LNzTK_gOin&t=1057
Personally, I think it's really easy to forget, and it would be good to raise the alert level by one level.
=> raidboss: r8s increase alert level for followups

package-lock.json, package.json, plugin/CactbotEventSource/Properties/AssemblyInfo.cs, plugin/CactbotOverlay/Properties/AssemblyInfo.cs
Breaking changes to support 7.3 signatures and memory offsets.
=> build: Bump version to 0.35.0

resources/zone_info.ts, util/coverage/coverage.ts
`npm run generate`... and coverage.ts
=> resources: KO 7.25
