OverlayPlugin/cactbot

docs/TimelineGuide.md

...of Cactbot Highlight,
Since it is implemented already in the latest release

docs: remove future work for new keywords

---

docs/zh-CN/README.md

fix an errorly replaced link caused by #20

i18n: fix zh-cn readme link error

---

ui/raidboss/data/03-hw/raid/a7s.ts
ui/raidboss/data/03-hw/trial/zurvan-ex.ts
ui/raidboss/data/04-sb/raid/o11n.ts
ui/raidboss/data/04-sb/raid/o12n.ts
ui/raidboss/data/04-sb/raid/o9n.ts
ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.ts
ui/raidboss/data/05-shb/trial/hades-ex.ts
ui/raidboss/data/06-ew/alliance/thaleia.ts
ui/raidboss/data/06-ew/dungeon/another_aloalo_island-savage.ts
ui/raidboss/data/06-ew/dungeon/another_aloalo_island.ts
ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane-savage.ts
ui/raidboss/data/06-ew/dungeon/another_sildihn_subterrane.ts
ui/raidboss/data/06-ew/dungeon/the_lunar_subterrane.ts
ui/raidboss/data/06-ew/raid/p11n.ts
ui/raidboss/data/06-ew/raid/p11s.ts
ui/raidboss/data/06-ew/raid/p12n.ts
ui/raidboss/data/06-ew/raid/p12s.ts
ui/raidboss/data/06-ew/raid/p6n.ts
ui/raidboss/data/06-ew/raid/p7n.ts
ui/raidboss/data/06-ew/raid/p8n.ts
ui/raidboss/data/06-ew/raid/p9n.ts
ui/raidboss/data/06-ew/raid/p9s.ts
ui/raidboss/data/06-ew/trial/golbez.ts
ui/raidboss/data/06-ew/trial/rubicante-ex.ts
ui/raidboss/data/06-ew/trial/rubicante.ts
ui/raidboss/data/06-ew/trial/zeromus.ts
ui/raidboss/data/06-ew/trial/zurvan-un.ts
ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts
util/logtools/web_splitter.ts

+ fixed some missingTranslation labels

i18n: added new translations 

---

ui/raidboss/data/06-ew/dungeon/mount_rokkon.ts
ui/raidboss/data/06-ew/ultimate/the_omega_protocol.ts

Fixes last missing translations.
Now FR should be up-to-date \o/

i18n: FR Translation update (10)

---

docs/LogGuide.md
resources/netlog_defs.ts
util/gen_log_guide.ts

ref. https://github.com/OverlayPlugin/OverlayPlugin/pull/284

docs: add documentation for 265 ContentFinderSettings line

---

ui/raidboss/data/06-ew/trial/asura.ts
ui/raidboss/data/06-ew/trial/asura.txt

Thanks so much wexxlee for getting the triggers in place so quickly!
I was lucky enough to get a 9-minute pull in-game and the timeline seemed okay. Please do check that I haven't misplaced any abilities when accounting for multiple possibilities in a given line. Overall I feel good about this after seeing it in-game, but it's very likely I've missed something.
cc @wexxlee @valarnin

raidboss: The Gilded Araya timeline

---

.github/workflows/release.yml

Sorry for the fast follow, but #62 had a small error in one of the job steps that I didn't catch earlier.  This should fix it (confirmed with re-testing).

ci: fix conditional in release workflow

---

ui/raidboss/data/02-arr/dungeon/haukke_manor.ts
ui/raidboss/data/02-arr/raid/t8.ts
ui/raidboss/data/02-arr/trial/ifrit-nm.ts
ui/raidboss/data/02-arr/trial/ifrit-nm.txt

Ref #84 
Re: Haukke Manor - the void lamps & lady's candles were [removed in Patch 6.1](https://ffxiv.gamerescape.com/wiki/Haukke_Manor#Dialogue), hence the deletion.

raidboss: replace GameLog lines (ARR)

---

ui/raidboss/data/04-sb/alliance/orbonne_monastery.txt
ui/raidboss/data/04-sb/alliance/royal_city_of_rabanastre.txt
ui/raidboss/data/04-sb/dungeon/fractal_continuum_hard.txt
ui/raidboss/data/04-sb/eureka/eureka_anemos.ts
ui/raidboss/data/04-sb/eureka/eureka_hydatos.ts
ui/raidboss/data/04-sb/eureka/eureka_pagos.ts
ui/raidboss/data/04-sb/eureka/eureka_pyros.ts
ui/raidboss/data/04-sb/raid/o11n.txt
ui/raidboss/data/04-sb/raid/o12n.txt
ui/raidboss/data/04-sb/raid/o12s.txt
ui/raidboss/data/04-sb/raid/o9n.txt
ui/raidboss/data/04-sb/trial/byakko-ex.ts
ui/raidboss/data/04-sb/trial/tsukuyomi-ex.ts

Wasn't able to do much with the eureka stuff because we just don't have the log lines to replace the `GameLog` triggers.  See comments, particularly in `eureka_hydatos.ts`.

raidboss: replace GameLog lines (SB)

---

docs/TimelineGuide.md
ui/raidboss/data/05-shb/eureka/bozjan_southern_front.txt

raidboss: fix bug in bozja CLL timeline

---

test/helper/test_timeline.ts
ui/raidboss/data/04-sb/dungeon/ala_mhigo.txt
ui/raidboss/data/04-sb/dungeon/bardams_mettle.txt
ui/raidboss/data/04-sb/dungeon/castrum_abania.txt
ui/raidboss/data/04-sb/dungeon/doma_castle.txt
ui/raidboss/data/04-sb/dungeon/drowned_city_of_skalla.txt
ui/raidboss/data/04-sb/dungeon/fractal_continuum_hard.txt
ui/raidboss/data/04-sb/dungeon/ghimlyt_dark.txt
ui/raidboss/data/04-sb/dungeon/ghimlyt_dark64.txt
ui/raidboss/data/04-sb/dungeon/swallows_compass.txt
ui/raidboss/data/04-sb/raid/o11n.txt
ui/raidboss/data/04-sb/raid/o12s.txt
ui/raidboss/data/04-sb/raid/o3n.txt
ui/raidboss/data/04-sb/raid/o6s.txt
ui/raidboss/data/04-sb/raid/o9n.txt
ui/raidboss/data/04-sb/trial/lakshmi.txt
ui/raidboss/data/04-sb/trial/suzaku.txt
ui/raidboss/data/04-sb/ultimate/unending_coil_ultimate.txt

ci/raidboss: timeline float lint 2: lint harder (sb)

---

test/helper/test_timeline.ts
ui/raidboss/data/02-arr/trial/titan-hm.txt
ui/raidboss/data/02-arr/trial/titan-nm.txt
ui/raidboss/data/02-arr/trial/ultima-ex.txt
ui/raidboss/data/03-hw/alliance/dun_scaith.txt
ui/raidboss/data/03-hw/alliance/weeping_city.txt
ui/raidboss/data/03-hw/dungeon/aetherochemical_research_facility.txt
ui/raidboss/data/03-hw/dungeon/baelsars_wall.txt
ui/raidboss/data/03-hw/dungeon/fractal_continuum.txt
ui/raidboss/data/03-hw/dungeon/gubal_library_hard.txt
ui/raidboss/data/03-hw/dungeon/sohm_al.txt
ui/raidboss/data/03-hw/dungeon/the_lost_city_of_amdapor_hard.txt

See #110.  Trilogy complete.  No more sequels.

ci/raidboss: floatlint 3: return of the float lint (arr+hw)

---

plugin/CactbotEventSource/FFXIVProcessKo.cs

plugin: ko 6.5 FFXIVProcessKo.cs update

---

types/event.d.ts

docs: Change type of charID in `ChangePrimaryPlayer` event

---

util/logtools/web_splitter.ts

i18n: FR update

---

docs/LogGuide.md

This is a follow-up to #141
- Change the Data Flow diagram to use SVG format for better readability.
- Update some header levels.
- Generate new Table-of-Contents (this should have been done in #141 but was missed).

docs: update Log Guide TOC

---

ui/raidboss/data/04-sb/ultimate/ultima_weapon_ultimate.ts

- Added missing Japanese translations to Ultima Weapon Ultimate
I created the translations for my own challenge.
This is my first pull request, so please let me know if I'm doing anything wrong.

i18n: ja ultima weapon ultimate

---

ui/raidboss/emulator/data/RaidEmulator.ts
ui/raidboss/emulator/overrides/RaidEmulatorPopupText.ts

raidemulator: Fix bug with set parser language

---

resources/party.ts

This is grabbed from #175 which I accidentally merged.

i18n: add jobs name translations

---

ui/oopsyraidsy/data/07-dt/trial/valigarmanda-ex.ts
ui/raidboss/data/07-dt/trial/valigarmanda-ex.ts
ui/raidboss/data/07-dt/trial/valigarmanda-ex.txt

Edit: This should be mostly done now.  Triggers are complete, timeline looks good (huge thanks to @valarnin).  There's some bare-bones oopsy that really only covers the first couple minutes of the fight -- I may try to add more tomorrow, but that might also be a follow-up PR so we can get this out.
I've tested against a number of logs in raidemulator with vod, and things generally look good.  But this would certainly benefit from more in-game testing.

raidboss: initial ex1

---

ui/dps/rdmty/dps.css

dps: update rdmty with vpr/pct job colors

---

ui/jobs/components/nin.ts
ui/jobs/jobs.css

fix kazematoi cannot stop pulsing and raidbuff overlaps with resource box.

jobs: NIN update pulse condition and raidbuff position

---

ui/jobs/combo_tracker.ts
ui/jobs/constants.ts

DRG and SAM got basic combo upgrade.
Other new advanced combo won't breaks basic combo, seems hard to track (and not worth tracking).

jobs: update combo tracker

---

package-lock.json
package.json
plugin/CactbotEventSource/Properties/AssemblyInfo.cs
plugin/CactbotOverlay/Properties/AssemblyInfo.cs

EDIT: wait for #216 to be merged

build: Bump version to 0.32.2

---

ui/jobs/components/whm.ts
ui/jobs/constants.ts
ui/jobs/jobs.css

- Add procbox for Presence of Mind
- Remove earlier patch diff

jobs: WHM DT changes

---

ui/jobs/components/sam.ts
ui/jobs/constants.ts

- Tsubame Gaeshi no longer have cooldown, spare this box for Ikishoten.

jobs: SAM DT changes

---

ui/jobs/components/mch.ts

- Drill chargeable (not tested)
- remove earlier patch diff

jobs: MCH DT changes

---

ui/jobs/components/sge.ts

- update DoT tracking for Eukrasian Dyskrasia
- remove earlier patch diff

jobs: SGE DT changes

---

resources/effect_id.ts
ui/jobs/components/vpr.ts
ui/jobs/player.ts
ui/jobs/utils.ts
util/gen_effect_id.ts

- Add VPR speedbuff Swiftscaled
- Add version diff for NIN speedbuff "Huton"and trait "Increase Attack Speed"
- Fix a bug that some speedbuff default set on True.

jobs: update DT speedbuff and fix default true

---

ui/jobs/components/drg.ts
ui/jobs/components/index.ts
ui/jobs/constants.ts
ui/jobs/jobs.css

- remove Dragon Sight, add Geirskogul timer.
- remove Blood gauge.
- add combo timer.
- adjust disembowel name and threhold.

jobs: DRG DT changes

---

ui/jobs/components/index.ts
ui/jobs/components/pld.ts
ui/jobs/constants.ts
ui/jobs/jobs.css

- Goring Blade merged into Fight or Flight, no longer require tracking.
- Add new timerbox for Circle of Scorn and Requiescat/Imperator.
- Remove Atonement stack box since they are converted to "Readies".
- Solve patch diffs.

jobs: PLD DT changes

---

plugin/CactbotEventSource/FFXIVProcessIntl.cs
types/event.d.ts
ui/jobs/components/index.ts
ui/jobs/components/mnk.ts
ui/jobs/constants.ts
ui/jobs/jobs.css
ui/test/test.ts

- update job memory
- add new fury gauge
- remove all previous timerbox and add Perfect Balance, Riddle of Fire, Riddle of Wind and Brotherhood timerbox.

jobs: MNK DT changes

---

plugin/CactbotEventSource/FFXIVProcessIntl.cs
types/event.d.ts
ui/jobs/components/ast.ts
ui/jobs/components/index.ts
ui/jobs/constants.ts
ui/jobs/jobs.css
ui/test/test.ts

- Update AstrologianJobMemory.
- Remove play card indicators.
- Change Sign gauge to Card gauge.
- Update Draw cooldown tracker and remove Crown Draw tracker, also add dynamic threhold.

jobs: AST DT changes

---

ui/jobs/player.ts

jobs: fix GCD calculation for non-globle GCD

---

ui/jobs/components/dnc.ts

jobs: DNC DT changes

---

ui/jobs/components/gnb.ts
ui/jobs/constants.ts

- add Lion combo support 
- adjust some threshold

jobs: GNB DT changes

---

ui/jobs/components/ast.ts
ui/jobs/components/mnk.ts
ui/jobs/jobs.ts

- MNK (Maximum stacks of Raptor's Fury and Coeurl's Fury changes)
- AST (Draw cooldown changes)

jobs: 7.01 changes

---

ui/jobs/components/mch.ts
ui/jobs/components/pct.ts

jobs: fix PCT/MCH chargeable AOE multicall

---

ui/raidboss/data/07-dt/raid/r3n.ts
ui/raidboss/data/07-dt/raid/r3n.txt

~~Needs testing still. Only checked the basics in raidemulator.~~
Tested in-zone, looks good.

raidboss: R3N initial triggers/timeline

---

ui/raidboss/data/07-dt/raid/r4n.ts
ui/raidboss/data/07-dt/raid/r4n.txt

Some TODOs. Still need to test in-instance and review video.

raidboss: Initial r4n

---

package-lock.json
package.json
plugin/CactbotEventSource/Properties/AssemblyInfo.cs
plugin/CactbotOverlay/Properties/AssemblyInfo.cs

I think we could hold off on merging this until closer to 5pm ET, in case there are additional i18n PRs for arcadion or more `jobs` PRs land.

build: Bump version to 0.32.3

---

ui/jobs/components/dnc.ts
ui/jobs/constants.ts

This action share a recast timer with Standard Step, missed in tracking.

jobs: DNC add Finising Move support

---

ui/jobs/combo_tracker.ts

- fix DRG second AOE combo reset combo timer.
- fix AOE hitting nothing doesn't reset combo timer.

jobs: fix combo tracker for AOE

---

resources/effect_id.ts
util/gen_effect_id.ts

Just a temporarily solution
Fix #280

resources: add no mercy in effect id

---

ui/jobs/jobs_options.ts
user/jobs-example.js

Didn't maintained for a very long time. Many outdated and no longer used options and broken options.

jobs: update outdated jobs options

---

ui/raidboss/data/07-dt/raid/r1s.txt

Tested vs local clear and against fflogs enrage.

raidboss: r1s Initial timeline

---

ui/raidboss/data/07-dt/raid/r3s.ts
ui/raidboss/data/07-dt/raid/r3s.txt

Also fix a minor issue in timeline, and add a TODO to the top of the file

raidboss: r3s add fooboom Special triggers

---

resources/netlog_defs.ts

Closes #310 - same as bug/fix in #265

resources: fix AbilityExtra log def

---

ui/raidboss/data/07-dt/raid/r1s.ts
ui/raidboss/data/07-dt/raid/r1s.txt

- Clean up map tiles to only the ones needed
- Fix issues with headmarkers and stack/spread callouts (sorry)
- Add triggers for Leaping <foo> mechanics
- Fix initial middle sync to have a window to combat early pullers
- Add Shockwave knockback trigger

raidboss: More r1s triggers/fixes

---

resources/outputs.ts
resources/util.ts
ui/raidboss/data/07-dt/raid/r4s.ts
ui/raidboss/data/07-dt/raid/r4s.txt

Timeline is done, barring a mistake somewhere.  Triggers are still wip - p1 is done, but doesn't have much p2 yet.  Planning to get at least a little more p2 in there before this gets merged.
This looks fine in raid emulator, but it could probably use some in-game testing if anyone is able to.  Worst case, we can merge and I can in-game test and adjust if needed on Tuesday.

raidboss: savage 4th floor

---

ui/oopsyraidsy/data/07-dt/dungeon/alexandria.ts
ui/raidboss/data/07-dt/dungeon/alexandria.ts
ui/raidboss/data/07-dt/dungeon/alexandria.txt

Tested in-game. 
This one should be relatively self-explanatory. TODOs are noted, but I'm happy to add others in if people think of them.

raidboss: Initial Alexandria Package

---

ui/raidboss/data/07-dt/raid/r2s.ts

Also fix missing callouts for alternate beeline/twist during beat phases

raidboss: Add heart debuff triggers

---

ui/raidboss/data/07-dt/raid/r4s.ts

In chinese, when using the Outputs defined will got:
- `靠近 => 靠近引导（小队远离）` : `In => Baits Close (Party Far)`
- `远离 => 靠近引导（小队靠近）`: `Out => Baits Far (Party Close)`
This can be confusing, so I'll use a custom output instead.

i18n: add r4s cn translate

---

package-lock.json
package.json
plugin/CactbotEventSource/Properties/AssemblyInfo.cs
plugin/CactbotOverlay/Properties/AssemblyInfo.cs

Ideally would like to merge this in the next few hours given weekly reset.  It would be great to include #325 if @valarnin or someone else has time to look at that, but fine either way.

build: Bump version to 0.32.6

---

ui/raidboss/data/07-dt/raid/r3s.ts

i18n: fix a translation error in r3s

---

ui/raidboss/data/07-dt/raid/r4s.ts

This PR adds Japanese translations to the existing R4S triggers.
Please review and let me know if any adjustments are needed.

i18n: Add Japanese translations for R4S triggers

---

ui/raidboss/data/07-dt/raid/r1s.ts
ui/raidboss/data/07-dt/raid/r2s.ts

This pull request adds missing Japanese translations for R1S and R2S triggers.

i18n: Add Japanese translations for R1S, R2S triggers

---

ui/raidboss/data/07-dt/raid/r2s.ts
ui/raidboss/data/07-dt/raid/r3s.ts

i18n: add CN translate for new triggers

---

ui/raidboss/data/07-dt/raid/r3s.ts

Since it takes too long for the bombarian special to reach the stack/spread, it can lead to forgetting, so a reminder has been added here.

raidboss: add r3s bombarian special reminder

---

ui/raidboss/data/07-dt/raid/r4s.ts

raidboss: add r4s aoe trigger

---

ui/raidboss/data/07-dt/hunts/shaaloani.ts

Keheni's forced march mech is another one where a countdown would be pretty useful.  Left a note in case #358 or something similar gets added.

raidboss: add Shaaloani A-rank hunt marks

---

ui/raidboss/data/07-dt/raid/r2s.ts
ui/raidboss/data/07-dt/raid/r3s.ts
ui/raidboss/data/07-dt/raid/r4s.ts

This pull request adds missing Japanese translations for R2S, R3S, R4S triggers.

i18n: Add Japanese translations for R2S, R3S, R4S triggers

---

resources/world_id.ts
resources/zone_info.ts

(This tracks with the hotfix notes indicating that the Shadow DC has been shut down.)

resources: 7.05h2 data file updates

---

ui/raidboss/data/07-dt/dungeon/alexandria.ts

raidboss: fix AntivirusX Interferon Collect

---

ui/raidboss/data/07-dt/hunts/heritage_found.ts

Fix "für" not being translated.

i18n: fix mistaken FR translation (Atticus)

---

ui/raidboss/data/07-dt/trial/zoraal-ja-ex.ts

The Chasm of Vollok callouts for the sword sync mechanic requires
identifying which diamonds are safe, along with avoiding a cleave that
hits the entire east or west half of the arena.
We cannot reasonably call every valid safe diamond, as this would make
the callout unusable.
Currently, the code prioritizes the inner diamonds, calling "inside
east diamond" or "inside west diamond". It also never calls the north or
south corner as safe.
My preferred strategy for this mechanic is to hover around the north or
south corner and move very slightly to adjust for the cleave into one of
the nearby safe diamonds.
Attempting to make this the default is not suitable, as many players are
likely already familiar with the existing callouts.
Introduce a configuration option to select the priority for …

raidboss: add chasm of vollok callout configuration

---

ui/oopsyraidsy/data/07-dt/raid/r4n.ts

oopsy: fix zoneId in r4n triggerSet

---

ui/raidboss/data/07-dt/raid/r1n.ts
ui/raidboss/data/07-dt/raid/r1s.ts

Closes #430.  (see comment there for bug explanation/fix).

raidboss: fix Mouser timing issue in R1N/R1S

---

ui/oopsyraidsy/player_state_tracker.ts

In prep for some feature improvements I'm hoping to make in oopsy, there were some bugs in party state tracking that need to be addressed first.
Because `oopsy_viewer` reads raw log lines to (re)assemble oopsy reports and isn't a true emulator, oopsy relies entirely on `PartyList` lines for its understanding of party composition, and simulates `PartyChanged` events based on that.  (Longer term, it'd be great to refactor the viewer and switch all of oopsy to event handling so this wouldn't be necessary, but that's a larger scope than I want to take on right now.)  But the current implementation regularly generates errors in the ACT OP log about not being able to locate player ids (including sometimes for the actual current player), and in general, oopsy's party-tracking has a few problems: …

oopsy: refactor (fix) party tracking

---

ui/oopsyraidsy/data/07-dt/dungeon/vanguard.ts
ui/raidboss/data/07-dt/dungeon/vanguard.ts
ui/raidboss/data/07-dt/dungeon/vanguard.txt

raidboss/oopsy: add Vanguard (L97)

---

ui/oopsyraidsy/data/07-dt/dungeon/skydeep-cenote.ts
ui/raidboss/data/07-dt/dungeon/skydeep-cenote.ts
ui/raidboss/data/07-dt/dungeon/skydeep-cenote.txt

raidboss/oopsy: add Skydeep Cenote (L95)

---

package-lock.json
package.json
plugin/CactbotEventSource/Properties/AssemblyInfo.cs
plugin/CactbotOverlay/Properties/AssemblyInfo.cs

Hold until after maintenance in case of additional changes needed.

build: Bump version to 0.32.11

---

ui/raidboss/data/07-dt/trial/queen-eternal-ex.ts
ui/raidboss/data/07-dt/trial/queen-eternal-ex.txt

Extremely basic initial triggers.
Initial timeline.
Everything is untested in-game right now. Timelines were generated from FFLogs pulls and then heavily tweaked based on what I had available locally.

raidboss: ex3 initial

---

package-lock.json
package.json
plugin/CactbotEventSource/Properties/AssemblyInfo.cs
plugin/CactbotOverlay/Properties/AssemblyInfo.cs

build: Bump version to 0.33.1

---

docs/zh-CN/README.md

docs: fix broken link

---

package-lock.json
package.json
plugin/CactbotEventSource/Properties/AssemblyInfo.cs
plugin/CactbotOverlay/Properties/AssemblyInfo.cs

Hotfix for the FRU P2 Icicle Impact issue.  
We can merge #537 before merging this (once approved).  My remaining comment on it is trivial and can be addressed in a follow up PR.

build: Bump version to 0.33.3

---

ui/raidboss/data/07-dt/ultimate/futures_rewritten.ts
ui/raidboss/data/07-dt/ultimate/futures_rewritten.txt

Picking up a couple things from #537, plus some tweaks to the intermission/adds timeline.

raidboss: FRU P2+adds timeline tweaks

---

ui/raidboss/data/07-dt/alliance/cloud_of_darkness_chaotic.ts

Found an imported translation error which suit e9s but not here.
Translated other entries by the way.

i18n: cloud_of_darkness_chaotic cn

---

ui/oopsyraidsy/data/07-dt/alliance/jeuno-first-walk.ts
ui/raidboss/data/07-dt/alliance/jeuno-first-walk.ts
ui/raidboss/data/07-dt/alliance/jeuno-first-walk.txt

Tested in-game and against my local timelines. Plenty of room for improvement with triggers and oopsy, but I think it's good enough for a first pass once people have had a chance to review it.

raidboss/oopsy: Add Jeuno First Walk package

---

.github/workflows/update-gh-pages.yml

This might or might not fix the issue. I'm not sure exactly how I'd go about testing this.

util: Fix coverage report action

---

ui/raidboss/data/07-dt/alliance/cloud_of_darkness_chaotic.ts

i18n: cloud_of_darkness_chaotic jp

---

ui/raidboss/data/07-dt/trial/queen-eternal.ts
ui/raidboss/data/07-dt/trial/queen-eternal.txt

Apologies for the lateness on this one, there was a lot of fiddliness getting the timeline to work, and then in-game testing for it is kinda painful. It was tough to find motivation at multiple points while assembling this. 
The timeline isn't perfect but it's definitely Good Enough. Oopsy will be forthcoming Eventually.

raidboss: Add Interphos triggers/timeline

---

util/coverage/coverage.d.ts
util/coverage/coverage.ts
util/gen_coverage_report.ts

- Tooltips were still not quite correct, fixed them
- Tags weren't sorted properly
- simple-git interactions simplified
- Fixed bug with unreleased status for zones where all files have pending changes for next release
- Fixed edge case where no skeleton file for zone was initially added, so pending PRs weren't being picked up
~~Still tweaking/testing changes for this one.~~
Should be good for review now.

util: More coverage report tweaks

---

ui/raidboss/data/07-dt/ultimate/futures_rewritten.ts

WIP:
- P2 Sinbound Holy Rotation
- TriggerSet

i18n: add FRU P2-P3 cn translate

---

ui/raidboss/raidboss.ts

Given the amount of questions/requests around this recently in Discord, I figured this should just be an actual option at this point.

raidboss: Add query param to set remote raidboss

---

package-lock.json
package.json
plugin/CactbotEventSource/Properties/AssemblyInfo.cs
plugin/CactbotOverlay/Properties/AssemblyInfo.cs

build: Bump version to 0.33.8

---

plugin/CactbotEventSource/FFXIVProcessKo.cs

same as https://github.com/OverlayPlugin/cactbot/pull/496

plugin: update signatures and memory for ko 7.1

---

ui/raidboss/data/07-dt/ultimate/futures_rewritten.ts

Forgot to update the comment with the last PR.
NB.  I have a couple of aoe triggers for p5, but nothing for the big mechs.  I will try to find some time this week to clean up and PR the stuff I have, but my group was done a while ago and I'm not likely to be back anytime soon.

raidboss: update FRU triggerSet comment

---

package-lock.json
package.json
plugin/CactbotEventSource/Properties/AssemblyInfo.cs
plugin/CactbotOverlay/Properties/AssemblyInfo.cs

Bumping to support the (breaking) struct changes for 7.2.

build: Bump version to 0.34.0

---

ui/oopsyraidsy/data/07-dt/raid/r5n.ts
ui/oopsyraidsy/data/07-dt/raid/r5s.ts
ui/oopsyraidsy/data/07-dt/raid/r6n.ts
ui/oopsyraidsy/data/07-dt/raid/r6s.ts
ui/oopsyraidsy/data/07-dt/raid/r7n.ts
ui/oopsyraidsy/data/07-dt/raid/r7s.ts
ui/oopsyraidsy/data/07-dt/raid/r8n.ts
ui/oopsyraidsy/data/07-dt/raid/r8s.ts
ui/oopsyraidsy/data/07-dt/trial/zelenia-ex.ts
ui/oopsyraidsy/data/07-dt/trial/zelenia.ts
ui/raidboss/data/07-dt/raid/r5n.ts
ui/raidboss/data/07-dt/raid/r5n.txt
ui/raidboss/data/07-dt/raid/r5s.ts
ui/raidboss/data/07-dt/raid/r5s.txt
ui/raidboss/data/07-dt/raid/r6n.ts
ui/raidboss/data/07-dt/raid/r6n.txt
ui/raidboss/data/07-dt/raid/r6s.ts
ui/raidboss/data/07-dt/raid/r6s.txt
ui/raidboss/data/07-dt/raid/r7n.ts
ui/raidboss/data/07-dt/raid/r7n.txt
ui/raidboss/data/07-dt/raid/r7s.ts
ui/raidboss/data/07-dt/raid/r7s.txt
ui/raidboss/data/07-dt/raid/r8n.ts
ui/raidboss/data/07-dt/raid/r8n.txt
ui/raidboss/data/07-dt/raid/r8s.ts
ui/raidboss/data/07-dt/raid/r8s.txt
ui/raidboss/data/07-dt/trial/zelenia-ex.ts
ui/raidboss/data/07-dt/trial/zelenia-ex.txt
ui/raidboss/data/07-dt/trial/zelenia.ts
ui/raidboss/data/07-dt/trial/zelenia.txt

Didn't do the dungeon, ran out of time.

raidboss: Add 7.2 skeleton files

---

ui/raidboss/data/07-dt/trial/zelenia-ex.ts
ui/raidboss/data/07-dt/trial/zelenia-ex.txt

~~Extremely WIP still.~~
~~Timeline entries past 569.9 are pulled from an fflogs enrage pull, but there didn't appear to be any drift issue in this fight for local vs fflogs timing so they should be fine.~~
Should be ready for review now.

raidboss: Zelenia Ex

---

package-lock.json
package.json
plugin/CactbotEventSource/Properties/AssemblyInfo.cs
plugin/CactbotOverlay/Properties/AssemblyInfo.cs

build: Bump version to 0.34.1

---

ui/raidboss/data/07-dt/raid/r5n.ts
ui/raidboss/data/07-dt/raid/r5n.txt

Included my notes on mapeffect info and headmarker info in case they're useful for other triggers or for savage.
Don't plan to add any more triggers to this PR, it's just the most basic of basics. This PR is more for the timeline.

raidboss: R5N timeline, basic triggers

---

ui/raidboss/data/07-dt/raid/r6n.ts
ui/raidboss/data/07-dt/raid/r6n.txt

Again, including my notes for MapEffect data and headmarker data, as well as a note with regards to the bomb/arrow stuff and `ActorSetPos`.

raidboss: R6N timeline, basic triggers

---

resources/outputs.ts
ui/raidboss/data/07-dt/raid/r5s.ts

Some initial (wip) M5S triggers.  Still in progress, will be testing in-game in a few hours.  I'll likely leave the to-dos unaddressed for now and handle in a later PR (or leave it for someone else).

raidboss: initial m5s triggers

---

ui/raidboss/data/07-dt/raid/r5s.ts

raidboss: add M5s merge order call

---

ui/raidboss/data/07-dt/raid/r6s.ts
ui/raidboss/data/07-dt/raid/r6s.txt

( the PR of the Beast \m/ )
also closes #664

raidboss: More M6S

---

ui/raidboss/data/07-dt/raid/r6s.ts

closes #671 
Also improves the callout for Taste of Fire/Taste of Thunder.

raidboss: fix Double Style trigger

---

resources/zone_info.ts

resources: KO 7.11

---

ui/raidboss/data/07-dt/trial/zelenia-ex.ts

This PR adds Japanese translations for ui/raidboss/data/07-dt/trial/zelenia-ex.ts.
Thank you for your time, and I’d appreciate your review!

i18n: Add JA translations to zelenia-ex

---

resources/outputs.ts

A minor annoyance that's been bugging me.

resources: normalize capitalization in `outputs`

---

ui/raidboss/data/07-dt/raid/r6s.ts

These are completely untested in-game and should be tested properly before merging. I don't have a lot of footage of R6S to compare against for verification of these, apparently I just didn't record any of my prog past adds so I only have two pulls to check against, but they both look correct.
Thundercloud triggers might be susceptible to lag issues.
Tower triggers, like half of the MapEffect locations were guesses based on patterns.

raidboss: Add R6S thundercloud and tower triggers

---

ui/raidboss/data/07-dt/raid/r8s.ts
ui/raidboss/data/07-dt/raid/r8s.txt

Addresses @valarnin's feedback from #656

raidboss: r8s timeline fixes and comments

---

package-lock.json
package.json
plugin/CactbotEventSource/Properties/AssemblyInfo.cs
plugin/CactbotOverlay/Properties/AssemblyInfo.cs

build: Bump version to 0.34.6

---

ui/raidboss/data/07-dt/raid/r7s.ts

Credit to @valarnin from discord.
It is a lot of text, but potentially one could override the default output and future PR could add config options for common strats (Hector / Kindred examples).

raidboss: r7s add pollen (roots) callout

---

package-lock.json
package.json
plugin/CactbotEventSource/Properties/AssemblyInfo.cs
plugin/CactbotOverlay/Properties/AssemblyInfo.cs

It's been over a month since the last release, so I took the liberty of opening this PR.

build: Bump version to 0.34.7

---

plugin/CactbotEventSource/FFXIVProcessKo.cs

plugin: KO 7.2 signatures and memory

---

ui/raidboss/data/07-dt/trial/necron-ex.ts
ui/raidboss/data/07-dt/trial/necron-ex.txt

Still a ton of work to do on this. Not sure if I'll have more time to work on it this weekend or not, if someone else wants to pick this up from here feel free.
Actor positions are tracked for hands and orbs in p2.

raidboss: WIP EX5
